<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iam/v1/hub.proto

namespace Iam\V1\PasswordSchema;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 重置密码请求：支持初次设置、正常重置与异常重置三种情况，注意要检查当前的访问凭证（如果是登录状态，将检查 Proof 与当前账号关系）
 *
 * Generated from protobuf message <code>iam.v1.PasswordSchema.ResetByProof</code>
 */
class ResetByProof extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.iam.v1.ExchangeID exchange_id = 1;</code>
     */
    protected $exchange_id = null;
    /**
     * 验证码
     *
     * Generated from protobuf field <code>string secret = 2 [(.validate.rules) = {</code>
     */
    protected $secret = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Iam\V1\ExchangeID $exchange_id
     *     @type string $secret
     *           验证码
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Iam\V1\Hub::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.iam.v1.ExchangeID exchange_id = 1;</code>
     * @return \Iam\V1\ExchangeID|null
     */
    public function getExchangeId()
    {
        return $this->exchange_id;
    }

    public function hasExchangeId()
    {
        return isset($this->exchange_id);
    }

    public function clearExchangeId()
    {
        unset($this->exchange_id);
    }

    /**
     * Generated from protobuf field <code>.iam.v1.ExchangeID exchange_id = 1;</code>
     * @param \Iam\V1\ExchangeID $var
     * @return $this
     */
    public function setExchangeId($var)
    {
        GPBUtil::checkMessage($var, \Iam\V1\ExchangeID::class);
        $this->exchange_id = $var;

        return $this;
    }

    /**
     * 验证码
     *
     * Generated from protobuf field <code>string secret = 2 [(.validate.rules) = {</code>
     * @return string
     */
    public function getSecret()
    {
        return $this->secret;
    }

    /**
     * 验证码
     *
     * Generated from protobuf field <code>string secret = 2 [(.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setSecret($var)
    {
        GPBUtil::checkString($var, True);
        $this->secret = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ResetByProof::class, \Iam\V1\PasswordSchema_ResetByProof::class);

