<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iam/v1/hub.proto

namespace Iam\V1\PasswordSchema;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 重置密码请求：仅适用于账号主体忘记密码自行重置
 *
 * Generated from protobuf message <code>iam.v1.PasswordSchema.ResetBySQAs</code>
 */
class ResetBySQAs extends \Google\Protobuf\Internal\Message
{
    /**
     *
     * Generated from protobuf field <code>string secret = 1 [(.validate.rules) = {</code>
     */
    protected $secret = '';
    /**
     * 用户名，用户未登录时可以使用，忽略当前登录账号
     *
     * Generated from protobuf field <code>string userid = 2 [(.validate.rules) = {</code>
     */
    protected $userid = '';
    /**
     * 本次重置用户对安全问答的回答
     *
     * Generated from protobuf field <code>.iam.v1.SQAs SQAs = 3;</code>
     */
    protected $SQAs = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $secret
     *     @type string $userid
     *           用户名，用户未登录时可以使用，忽略当前登录账号
     *     @type \Iam\V1\SQAs $SQAs
     *           本次重置用户对安全问答的回答
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Iam\V1\Hub::initOnce();
        parent::__construct($data);
    }

    /**
     *
     * Generated from protobuf field <code>string secret = 1 [(.validate.rules) = {</code>
     * @return string
     */
    public function getSecret()
    {
        return $this->secret;
    }

    /**
     *
     * Generated from protobuf field <code>string secret = 1 [(.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setSecret($var)
    {
        GPBUtil::checkString($var, True);
        $this->secret = $var;

        return $this;
    }

    /**
     * 用户名，用户未登录时可以使用，忽略当前登录账号
     *
     * Generated from protobuf field <code>string userid = 2 [(.validate.rules) = {</code>
     * @return string
     */
    public function getUserid()
    {
        return $this->userid;
    }

    /**
     * 用户名，用户未登录时可以使用，忽略当前登录账号
     *
     * Generated from protobuf field <code>string userid = 2 [(.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setUserid($var)
    {
        GPBUtil::checkString($var, True);
        $this->userid = $var;

        return $this;
    }

    /**
     * 本次重置用户对安全问答的回答
     *
     * Generated from protobuf field <code>.iam.v1.SQAs SQAs = 3;</code>
     * @return \Iam\V1\SQAs|null
     */
    public function getSQAs()
    {
        return $this->SQAs;
    }

    public function hasSQAs()
    {
        return isset($this->SQAs);
    }

    public function clearSQAs()
    {
        unset($this->SQAs);
    }

    /**
     * 本次重置用户对安全问答的回答
     *
     * Generated from protobuf field <code>.iam.v1.SQAs SQAs = 3;</code>
     * @param \Iam\V1\SQAs $var
     * @return $this
     */
    public function setSQAs($var)
    {
        GPBUtil::checkMessage($var, \Iam\V1\SQAs::class);
        $this->SQAs = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ResetBySQAs::class, \Iam\V1\PasswordSchema_ResetBySQAs::class);

