<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iam/v1/hub.proto

namespace Iam\V1\PasswordSchema;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>iam.v1.PasswordSchema.ResetRequest</code>
 */
class ResetRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * 新密码
     *
     * Generated from protobuf field <code>string password = 1 [(.validate.rules) = {</code>
     */
    protected $password = '';
    /**
     * 密码提示
     *
     * Generated from protobuf field <code>string hint = 2 [(.validate.rules) = {</code>
     */
    protected $hint = '';
    protected $request;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $password
     *           新密码
     *     @type string $hint
     *           密码提示
     *     @type \Iam\V1\PasswordSchema\ResetByProof $request_by_proof
     *     @type \Iam\V1\PasswordSchema\ResetByPassword $request_by_password
     *     @type \Iam\V1\PasswordSchema\ResetBySQAs $request_by_SQAs
     *     @type \Iam\V1\PasswordSchema\ResetByOwner $request_by_owner
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Iam\V1\Hub::initOnce();
        parent::__construct($data);
    }

    /**
     * 新密码
     *
     * Generated from protobuf field <code>string password = 1 [(.validate.rules) = {</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * 新密码
     *
     * Generated from protobuf field <code>string password = 1 [(.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     * 密码提示
     *
     * Generated from protobuf field <code>string hint = 2 [(.validate.rules) = {</code>
     * @return string
     */
    public function getHint()
    {
        return $this->hint;
    }

    /**
     * 密码提示
     *
     * Generated from protobuf field <code>string hint = 2 [(.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setHint($var)
    {
        GPBUtil::checkString($var, True);
        $this->hint = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.iam.v1.PasswordSchema.ResetByProof request_by_proof = 3;</code>
     * @return \Iam\V1\PasswordSchema\ResetByProof|null
     */
    public function getRequestByProof()
    {
        return $this->readOneof(3);
    }

    public function hasRequestByProof()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.iam.v1.PasswordSchema.ResetByProof request_by_proof = 3;</code>
     * @param \Iam\V1\PasswordSchema\ResetByProof $var
     * @return $this
     */
    public function setRequestByProof($var)
    {
        GPBUtil::checkMessage($var, \Iam\V1\PasswordSchema\ResetByProof::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.iam.v1.PasswordSchema.ResetByPassword request_by_password = 4;</code>
     * @return \Iam\V1\PasswordSchema\ResetByPassword|null
     */
    public function getRequestByPassword()
    {
        return $this->readOneof(4);
    }

    public function hasRequestByPassword()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.iam.v1.PasswordSchema.ResetByPassword request_by_password = 4;</code>
     * @param \Iam\V1\PasswordSchema\ResetByPassword $var
     * @return $this
     */
    public function setRequestByPassword($var)
    {
        GPBUtil::checkMessage($var, \Iam\V1\PasswordSchema\ResetByPassword::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.iam.v1.PasswordSchema.ResetBySQAs request_by_SQAs = 5;</code>
     * @return \Iam\V1\PasswordSchema\ResetBySQAs|null
     */
    public function getRequestBySQAs()
    {
        return $this->readOneof(5);
    }

    public function hasRequestBySQAs()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.iam.v1.PasswordSchema.ResetBySQAs request_by_SQAs = 5;</code>
     * @param \Iam\V1\PasswordSchema\ResetBySQAs $var
     * @return $this
     */
    public function setRequestBySQAs($var)
    {
        GPBUtil::checkMessage($var, \Iam\V1\PasswordSchema\ResetBySQAs::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.iam.v1.PasswordSchema.ResetByOwner request_by_owner = 6;</code>
     * @return \Iam\V1\PasswordSchema\ResetByOwner|null
     */
    public function getRequestByOwner()
    {
        return $this->readOneof(6);
    }

    public function hasRequestByOwner()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.iam.v1.PasswordSchema.ResetByOwner request_by_owner = 6;</code>
     * @param \Iam\V1\PasswordSchema\ResetByOwner $var
     * @return $this
     */
    public function setRequestByOwner($var)
    {
        GPBUtil::checkMessage($var, \Iam\V1\PasswordSchema\ResetByOwner::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getRequest()
    {
        return $this->whichOneof("request");
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ResetRequest::class, \Iam\V1\PasswordSchema_ResetRequest::class);

