<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iam/v1/hub.proto

namespace Iam\V1\PasswordSchema;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 重置密码请求：适用于主账号重置子账号密码，要检查当前账号访问凭证
 *
 * Generated from protobuf message <code>iam.v1.PasswordSchema.ResetByOwner</code>
 */
class ResetByOwner extends \Google\Protobuf\Internal\Message
{
    /**
     * 要重置的子账号 openid
     *
     * Generated from protobuf field <code>string openid = 1 [(.validate.rules) = {</code>
     */
    protected $openid = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $openid
     *           要重置的子账号 openid
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Iam\V1\Hub::initOnce();
        parent::__construct($data);
    }

    /**
     * 要重置的子账号 openid
     *
     * Generated from protobuf field <code>string openid = 1 [(.validate.rules) = {</code>
     * @return string
     */
    public function getOpenid()
    {
        return $this->openid;
    }

    /**
     * 要重置的子账号 openid
     *
     * Generated from protobuf field <code>string openid = 1 [(.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setOpenid($var)
    {
        GPBUtil::checkString($var, True);
        $this->openid = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ResetByOwner::class, \Iam\V1\PasswordSchema_ResetByOwner::class);

