<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/schema.proto

namespace Im\V1\User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 用户位映射表
 *
 * Generated from protobuf message <code>im.v1.User.Bitmap</code>
 */
class Bitmap extends \Google\Protobuf\Internal\Message
{
    /**
     * 用户表版本号
     *
     * Generated from protobuf field <code>uint64 version = 1;</code>
     */
    protected $version = 0;
    /**
     * 字节映射数据
     *
     * Generated from protobuf field <code>bytes data = 2;</code>
     */
    protected $data = '';
    /**
     * 群组号，省略则使用会话关联的群组
     *
     * Generated from protobuf field <code>string group_id = 3;</code>
     */
    protected $group_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $version
     *           用户表版本号
     *     @type string $data
     *           字节映射数据
     *     @type string $group_id
     *           群组号，省略则使用会话关联的群组
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Im\V1\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * 用户表版本号
     *
     * Generated from protobuf field <code>uint64 version = 1;</code>
     * @return int|string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * 用户表版本号
     *
     * Generated from protobuf field <code>uint64 version = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkUint64($var);
        $this->version = $var;

        return $this;
    }

    /**
     * 字节映射数据
     *
     * Generated from protobuf field <code>bytes data = 2;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * 字节映射数据
     *
     * Generated from protobuf field <code>bytes data = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->data = $var;

        return $this;
    }

    /**
     * 群组号，省略则使用会话关联的群组
     *
     * Generated from protobuf field <code>string group_id = 3;</code>
     * @return string
     */
    public function getGroupId()
    {
        return $this->group_id;
    }

    /**
     * 群组号，省略则使用会话关联的群组
     *
     * Generated from protobuf field <code>string group_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupId($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_id = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Bitmap::class, \Im\V1\User_Bitmap::class);

