<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iam/v1/hub.proto

namespace Iam\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 访问凭证
 *
 * Generated from protobuf message <code>iam.v1.AccessToken</code>
 */
class AccessToken extends \Google\Protobuf\Internal\Message
{
    /**
     * JWT 字符串
     *
     * Generated from protobuf field <code>string jwt = 1;</code>
     */
    protected $jwt = '';
    /**
     * 账号
     *
     * Generated from protobuf field <code>string openid = 2 [(.validate.rules) = {</code>
     */
    protected $openid = '';
    /**
     * 归属地
     *
     * Generated from protobuf field <code>string host = 3 [(.validate.rules) = {</code>
     */
    protected $host = '';
    /**
     * 过期时间
     *
     * Generated from protobuf field <code>int64 expire_at = 4;</code>
     */
    protected $expire_at = 0;
    /**
     * 刷新凭证
     *
     * Generated from protobuf field <code>.iam.v1.RefreshToken refresh_token = 5;</code>
     */
    protected $refresh_token = null;
    /**
     * 适用的范围
     *
     * Generated from protobuf field <code>repeated string scope = 6;</code>
     */
    private $scope;
    /**
     * 融云令牌
     *
     * Generated from protobuf field <code>string rong_cloud_token = 7;</code>
     */
    protected $rong_cloud_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $jwt
     *           JWT 字符串
     *     @type string $openid
     *           账号
     *     @type string $host
     *           归属地
     *     @type int|string $expire_at
     *           过期时间
     *     @type \Iam\V1\RefreshToken $refresh_token
     *           刷新凭证
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $scope
     *           适用的范围
     *     @type string $rong_cloud_token
     *           融云令牌
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Iam\V1\Hub::initOnce();
        parent::__construct($data);
    }

    /**
     * JWT 字符串
     *
     * Generated from protobuf field <code>string jwt = 1;</code>
     * @return string
     */
    public function getJwt()
    {
        return $this->jwt;
    }

    /**
     * JWT 字符串
     *
     * Generated from protobuf field <code>string jwt = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setJwt($var)
    {
        GPBUtil::checkString($var, True);
        $this->jwt = $var;

        return $this;
    }

    /**
     * 账号
     *
     * Generated from protobuf field <code>string openid = 2 [(.validate.rules) = {</code>
     * @return string
     */
    public function getOpenid()
    {
        return $this->openid;
    }

    /**
     * 账号
     *
     * Generated from protobuf field <code>string openid = 2 [(.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setOpenid($var)
    {
        GPBUtil::checkString($var, True);
        $this->openid = $var;

        return $this;
    }

    /**
     * 归属地
     *
     * Generated from protobuf field <code>string host = 3 [(.validate.rules) = {</code>
     * @return string
     */
    public function getHost()
    {
        return $this->host;
    }

    /**
     * 归属地
     *
     * Generated from protobuf field <code>string host = 3 [(.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->host = $var;

        return $this;
    }

    /**
     * 过期时间
     *
     * Generated from protobuf field <code>int64 expire_at = 4;</code>
     * @return int|string
     */
    public function getExpireAt()
    {
        return $this->expire_at;
    }

    /**
     * 过期时间
     *
     * Generated from protobuf field <code>int64 expire_at = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpireAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->expire_at = $var;

        return $this;
    }

    /**
     * 刷新凭证
     *
     * Generated from protobuf field <code>.iam.v1.RefreshToken refresh_token = 5;</code>
     * @return \Iam\V1\RefreshToken|null
     */
    public function getRefreshToken()
    {
        return $this->refresh_token;
    }

    public function hasRefreshToken()
    {
        return isset($this->refresh_token);
    }

    public function clearRefreshToken()
    {
        unset($this->refresh_token);
    }

    /**
     * 刷新凭证
     *
     * Generated from protobuf field <code>.iam.v1.RefreshToken refresh_token = 5;</code>
     * @param \Iam\V1\RefreshToken $var
     * @return $this
     */
    public function setRefreshToken($var)
    {
        GPBUtil::checkMessage($var, \Iam\V1\RefreshToken::class);
        $this->refresh_token = $var;

        return $this;
    }

    /**
     * 适用的范围
     *
     * Generated from protobuf field <code>repeated string scope = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getScope()
    {
        return $this->scope;
    }

    /**
     * 适用的范围
     *
     * Generated from protobuf field <code>repeated string scope = 6;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setScope($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->scope = $arr;

        return $this;
    }

    /**
     * 融云令牌
     *
     * Generated from protobuf field <code>string rong_cloud_token = 7;</code>
     * @return string
     */
    public function getRongCloudToken()
    {
        return $this->rong_cloud_token;
    }

    /**
     * 融云令牌
     *
     * Generated from protobuf field <code>string rong_cloud_token = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setRongCloudToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->rong_cloud_token = $var;

        return $this;
    }

}

