<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iam/v1/hub.proto

namespace Iam\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>iam.v1.AccountSchema</code>
 */
class AccountSchema extends \Google\Protobuf\Internal\Message
{
    /**
     * &#64;gotags: gorm:"primaryKey" json:"-"
     *
     * Generated from protobuf field <code>int64 ID = 1;</code>
     */
    protected $ID = 0;
    /**
     * &#64;gotags: json:"id_owner"
     *
     * Generated from protobuf field <code>int64 id_owner = 2;</code>
     */
    protected $id_owner = 0;
    /**
     * &#64;gotags: json:"openid"
     *
     * Generated from protobuf field <code>string openid = 3;</code>
     */
    protected $openid = '';
    /**
     * &#64;gotags: json:"security"
     *
     * Generated from protobuf field <code>uint32 security = 4 [(.validate.rules) = {</code>
     */
    protected $security = 0;
    /**
     * &#64;gotags: json:"account"
     *
     * Generated from protobuf field <code>string account = 5;</code>
     */
    protected $account = '';
    /**
     * &#64;gotags: json:"account_updated"
     *
     * Generated from protobuf field <code>int64 account_updated = 6;</code>
     */
    protected $account_updated = 0;
    /**
     * &#64;gotags: json:"enabled"
     *
     * Generated from protobuf field <code>int64 enabled = 7;</code>
     */
    protected $enabled = 0;
    /**
     * &#64;gotags: json:"banned"
     *
     * Generated from protobuf field <code>int64 banned = 8;</code>
     */
    protected $banned = 0;
    /**
     * &#64;gotags: json:"removed"
     *
     * Generated from protobuf field <code>int64 removed = 9;</code>
     */
    protected $removed = 0;
    /**
     * &#64;gotags: gorm:"autoCreateTime" json:"created"
     *
     * Generated from protobuf field <code>int64 created = 10;</code>
     */
    protected $created = 0;
    /**
     * &#64;gotags: json:"latest"
     *
     * Generated from protobuf field <code>int64 latest = 11;</code>
     */
    protected $latest = 0;
    /**
     * &#64;gotags: json:"secret"
     *
     * Generated from protobuf field <code>string secret = 12;</code>
     */
    protected $secret = '';
    /**
     * &#64;gotags: json:"source"
     *
     * Generated from protobuf field <code>string source = 13;</code>
     */
    protected $source = '';
    /**
     * &#64;gotags: json:"main_device_sn"
     *
     * Generated from protobuf field <code>string main_device_sn = 14;</code>
     */
    protected $main_device_sn = '';
    /**
     * &#64;gotags: gorm:"serializer:json" json:"frozen"
     *
     * Generated from protobuf field <code>bytes badges = 15;</code>
     */
    protected $badges = '';
    /**
     * &#64;gotags: json:"frozen"
     *
     * Generated from protobuf field <code>int64 frozen = 16;</code>
     */
    protected $frozen = 0;
    /**
     * &#64;gotags: json:"reason"
     *
     * Generated from protobuf field <code>string reason = 17;</code>
     */
    protected $reason = '';
    /**
     * &#64;gotags: json:"email"
     *
     * Generated from protobuf field <code>string email = 18;</code>
     */
    protected $email = '';
    /**
     * &#64;gotags: json:"removed_at"
     *
     * Generated from protobuf field <code>int64 removed_at = 19;</code>
     */
    protected $removed_at = 0;
    /**
     * &#64;gotags: json:"region"
     *
     * Generated from protobuf field <code>string region = 20;</code>
     */
    protected $region = '';
    /**
     * &#64;gotags: gorm:"-" json:"title"
     *
     * Generated from protobuf field <code>string title = 21;</code>
     */
    protected $title = '';
    /**
     * &#64;gotags: gorm:"-" json:"avatar"
     *
     * Generated from protobuf field <code>string avatar = 22;</code>
     */
    protected $avatar = '';
    /**
     * &#64;gotags: gorm:"-" json:"cellphone"
     *
     * Generated from protobuf field <code>string cellphone = 23;</code>
     */
    protected $cellphone = '';
    /**
     * &#64;gotags: gorm:"-" json:"e_sign"
     *
     * Generated from protobuf field <code>.iam.v1.ESign e_sign = 24;</code>
     */
    protected $e_sign = null;
    /**
     * &#64;gotags: gorm:"-" json:"profile"
     *
     * Generated from protobuf field <code>.iam.v1.ProfileSchema profile = 25;</code>
     */
    protected $profile = null;
    /**
     * &#64;gotags: gorm:"-" json:"gender"
     *
     * Generated from protobuf field <code>.iam.v1.Gender gender = 26;</code>
     */
    protected $gender = 0;
    /**
     * &#64;gotags: gorm:"-" json:"region_code"
     *
     * Generated from protobuf field <code>string region_code = 27;</code>
     */
    protected $region_code = '';
    /**
     * &#64;gotags: gorm:"-" json:"org"
     *
     * Generated from protobuf field <code>repeated string orgs = 28;</code>
     */
    private $orgs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $ID
     *           &#64;gotags: gorm:"primaryKey" json:"-"
     *     @type int|string $id_owner
     *           &#64;gotags: json:"id_owner"
     *     @type string $openid
     *           &#64;gotags: json:"openid"
     *     @type int $security
     *           &#64;gotags: json:"security"
     *     @type string $account
     *           &#64;gotags: json:"account"
     *     @type int|string $account_updated
     *           &#64;gotags: json:"account_updated"
     *     @type int|string $enabled
     *           &#64;gotags: json:"enabled"
     *     @type int|string $banned
     *           &#64;gotags: json:"banned"
     *     @type int|string $removed
     *           &#64;gotags: json:"removed"
     *     @type int|string $created
     *           &#64;gotags: gorm:"autoCreateTime" json:"created"
     *     @type int|string $latest
     *           &#64;gotags: json:"latest"
     *     @type string $secret
     *           &#64;gotags: json:"secret"
     *     @type string $source
     *           &#64;gotags: json:"source"
     *     @type string $main_device_sn
     *           &#64;gotags: json:"main_device_sn"
     *     @type string $badges
     *           &#64;gotags: gorm:"serializer:json" json:"frozen"
     *     @type int|string $frozen
     *           &#64;gotags: json:"frozen"
     *     @type string $reason
     *           &#64;gotags: json:"reason"
     *     @type string $email
     *           &#64;gotags: json:"email"
     *     @type int|string $removed_at
     *           &#64;gotags: json:"removed_at"
     *     @type string $region
     *           &#64;gotags: json:"region"
     *     @type string $title
     *           &#64;gotags: gorm:"-" json:"title"
     *     @type string $avatar
     *           &#64;gotags: gorm:"-" json:"avatar"
     *     @type string $cellphone
     *           &#64;gotags: gorm:"-" json:"cellphone"
     *     @type \Iam\V1\ESign $e_sign
     *           &#64;gotags: gorm:"-" json:"e_sign"
     *     @type \Iam\V1\ProfileSchema $profile
     *           &#64;gotags: gorm:"-" json:"profile"
     *     @type int $gender
     *           &#64;gotags: gorm:"-" json:"gender"
     *     @type string $region_code
     *           &#64;gotags: gorm:"-" json:"region_code"
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $orgs
     *           &#64;gotags: gorm:"-" json:"org"
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Iam\V1\Hub::initOnce();
        parent::__construct($data);
    }

    /**
     * &#64;gotags: gorm:"primaryKey" json:"-"
     *
     * Generated from protobuf field <code>int64 ID = 1;</code>
     * @return int|string
     */
    public function getID()
    {
        return $this->ID;
    }

    /**
     * &#64;gotags: gorm:"primaryKey" json:"-"
     *
     * Generated from protobuf field <code>int64 ID = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setID($var)
    {
        GPBUtil::checkInt64($var);
        $this->ID = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"id_owner"
     *
     * Generated from protobuf field <code>int64 id_owner = 2;</code>
     * @return int|string
     */
    public function getIdOwner()
    {
        return $this->id_owner;
    }

    /**
     * &#64;gotags: json:"id_owner"
     *
     * Generated from protobuf field <code>int64 id_owner = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIdOwner($var)
    {
        GPBUtil::checkInt64($var);
        $this->id_owner = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"openid"
     *
     * Generated from protobuf field <code>string openid = 3;</code>
     * @return string
     */
    public function getOpenid()
    {
        return $this->openid;
    }

    /**
     * &#64;gotags: json:"openid"
     *
     * Generated from protobuf field <code>string openid = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOpenid($var)
    {
        GPBUtil::checkString($var, True);
        $this->openid = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"security"
     *
     * Generated from protobuf field <code>uint32 security = 4 [(.validate.rules) = {</code>
     * @return int
     */
    public function getSecurity()
    {
        return $this->security;
    }

    /**
     * &#64;gotags: json:"security"
     *
     * Generated from protobuf field <code>uint32 security = 4 [(.validate.rules) = {</code>
     * @param int $var
     * @return $this
     */
    public function setSecurity($var)
    {
        GPBUtil::checkUint32($var);
        $this->security = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"account"
     *
     * Generated from protobuf field <code>string account = 5;</code>
     * @return string
     */
    public function getAccount()
    {
        return $this->account;
    }

    /**
     * &#64;gotags: json:"account"
     *
     * Generated from protobuf field <code>string account = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setAccount($var)
    {
        GPBUtil::checkString($var, True);
        $this->account = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"account_updated"
     *
     * Generated from protobuf field <code>int64 account_updated = 6;</code>
     * @return int|string
     */
    public function getAccountUpdated()
    {
        return $this->account_updated;
    }

    /**
     * &#64;gotags: json:"account_updated"
     *
     * Generated from protobuf field <code>int64 account_updated = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAccountUpdated($var)
    {
        GPBUtil::checkInt64($var);
        $this->account_updated = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"enabled"
     *
     * Generated from protobuf field <code>int64 enabled = 7;</code>
     * @return int|string
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * &#64;gotags: json:"enabled"
     *
     * Generated from protobuf field <code>int64 enabled = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEnabled($var)
    {
        GPBUtil::checkInt64($var);
        $this->enabled = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"banned"
     *
     * Generated from protobuf field <code>int64 banned = 8;</code>
     * @return int|string
     */
    public function getBanned()
    {
        return $this->banned;
    }

    /**
     * &#64;gotags: json:"banned"
     *
     * Generated from protobuf field <code>int64 banned = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBanned($var)
    {
        GPBUtil::checkInt64($var);
        $this->banned = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"removed"
     *
     * Generated from protobuf field <code>int64 removed = 9;</code>
     * @return int|string
     */
    public function getRemoved()
    {
        return $this->removed;
    }

    /**
     * &#64;gotags: json:"removed"
     *
     * Generated from protobuf field <code>int64 removed = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRemoved($var)
    {
        GPBUtil::checkInt64($var);
        $this->removed = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"autoCreateTime" json:"created"
     *
     * Generated from protobuf field <code>int64 created = 10;</code>
     * @return int|string
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * &#64;gotags: gorm:"autoCreateTime" json:"created"
     *
     * Generated from protobuf field <code>int64 created = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreated($var)
    {
        GPBUtil::checkInt64($var);
        $this->created = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"latest"
     *
     * Generated from protobuf field <code>int64 latest = 11;</code>
     * @return int|string
     */
    public function getLatest()
    {
        return $this->latest;
    }

    /**
     * &#64;gotags: json:"latest"
     *
     * Generated from protobuf field <code>int64 latest = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLatest($var)
    {
        GPBUtil::checkInt64($var);
        $this->latest = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"secret"
     *
     * Generated from protobuf field <code>string secret = 12;</code>
     * @return string
     */
    public function getSecret()
    {
        return $this->secret;
    }

    /**
     * &#64;gotags: json:"secret"
     *
     * Generated from protobuf field <code>string secret = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setSecret($var)
    {
        GPBUtil::checkString($var, True);
        $this->secret = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"source"
     *
     * Generated from protobuf field <code>string source = 13;</code>
     * @return string
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * &#64;gotags: json:"source"
     *
     * Generated from protobuf field <code>string source = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->source = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"main_device_sn"
     *
     * Generated from protobuf field <code>string main_device_sn = 14;</code>
     * @return string
     */
    public function getMainDeviceSn()
    {
        return $this->main_device_sn;
    }

    /**
     * &#64;gotags: json:"main_device_sn"
     *
     * Generated from protobuf field <code>string main_device_sn = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setMainDeviceSn($var)
    {
        GPBUtil::checkString($var, True);
        $this->main_device_sn = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"serializer:json" json:"frozen"
     *
     * Generated from protobuf field <code>bytes badges = 15;</code>
     * @return string
     */
    public function getBadges()
    {
        return $this->badges;
    }

    /**
     * &#64;gotags: gorm:"serializer:json" json:"frozen"
     *
     * Generated from protobuf field <code>bytes badges = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setBadges($var)
    {
        GPBUtil::checkString($var, False);
        $this->badges = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"frozen"
     *
     * Generated from protobuf field <code>int64 frozen = 16;</code>
     * @return int|string
     */
    public function getFrozen()
    {
        return $this->frozen;
    }

    /**
     * &#64;gotags: json:"frozen"
     *
     * Generated from protobuf field <code>int64 frozen = 16;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFrozen($var)
    {
        GPBUtil::checkInt64($var);
        $this->frozen = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"reason"
     *
     * Generated from protobuf field <code>string reason = 17;</code>
     * @return string
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * &#64;gotags: json:"reason"
     *
     * Generated from protobuf field <code>string reason = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->reason = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"email"
     *
     * Generated from protobuf field <code>string email = 18;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * &#64;gotags: json:"email"
     *
     * Generated from protobuf field <code>string email = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"removed_at"
     *
     * Generated from protobuf field <code>int64 removed_at = 19;</code>
     * @return int|string
     */
    public function getRemovedAt()
    {
        return $this->removed_at;
    }

    /**
     * &#64;gotags: json:"removed_at"
     *
     * Generated from protobuf field <code>int64 removed_at = 19;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRemovedAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->removed_at = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"region"
     *
     * Generated from protobuf field <code>string region = 20;</code>
     * @return string
     */
    public function getRegion()
    {
        return $this->region;
    }

    /**
     * &#64;gotags: json:"region"
     *
     * Generated from protobuf field <code>string region = 20;</code>
     * @param string $var
     * @return $this
     */
    public function setRegion($var)
    {
        GPBUtil::checkString($var, True);
        $this->region = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"-" json:"title"
     *
     * Generated from protobuf field <code>string title = 21;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * &#64;gotags: gorm:"-" json:"title"
     *
     * Generated from protobuf field <code>string title = 21;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"-" json:"avatar"
     *
     * Generated from protobuf field <code>string avatar = 22;</code>
     * @return string
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    /**
     * &#64;gotags: gorm:"-" json:"avatar"
     *
     * Generated from protobuf field <code>string avatar = 22;</code>
     * @param string $var
     * @return $this
     */
    public function setAvatar($var)
    {
        GPBUtil::checkString($var, True);
        $this->avatar = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"-" json:"cellphone"
     *
     * Generated from protobuf field <code>string cellphone = 23;</code>
     * @return string
     */
    public function getCellphone()
    {
        return $this->cellphone;
    }

    /**
     * &#64;gotags: gorm:"-" json:"cellphone"
     *
     * Generated from protobuf field <code>string cellphone = 23;</code>
     * @param string $var
     * @return $this
     */
    public function setCellphone($var)
    {
        GPBUtil::checkString($var, True);
        $this->cellphone = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"-" json:"e_sign"
     *
     * Generated from protobuf field <code>.iam.v1.ESign e_sign = 24;</code>
     * @return \Iam\V1\ESign|null
     */
    public function getESign()
    {
        return $this->e_sign;
    }

    public function hasESign()
    {
        return isset($this->e_sign);
    }

    public function clearESign()
    {
        unset($this->e_sign);
    }

    /**
     * &#64;gotags: gorm:"-" json:"e_sign"
     *
     * Generated from protobuf field <code>.iam.v1.ESign e_sign = 24;</code>
     * @param \Iam\V1\ESign $var
     * @return $this
     */
    public function setESign($var)
    {
        GPBUtil::checkMessage($var, \Iam\V1\ESign::class);
        $this->e_sign = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"-" json:"profile"
     *
     * Generated from protobuf field <code>.iam.v1.ProfileSchema profile = 25;</code>
     * @return \Iam\V1\ProfileSchema|null
     */
    public function getProfile()
    {
        return $this->profile;
    }

    public function hasProfile()
    {
        return isset($this->profile);
    }

    public function clearProfile()
    {
        unset($this->profile);
    }

    /**
     * &#64;gotags: gorm:"-" json:"profile"
     *
     * Generated from protobuf field <code>.iam.v1.ProfileSchema profile = 25;</code>
     * @param \Iam\V1\ProfileSchema $var
     * @return $this
     */
    public function setProfile($var)
    {
        GPBUtil::checkMessage($var, \Iam\V1\ProfileSchema::class);
        $this->profile = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"-" json:"gender"
     *
     * Generated from protobuf field <code>.iam.v1.Gender gender = 26;</code>
     * @return int
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     * &#64;gotags: gorm:"-" json:"gender"
     *
     * Generated from protobuf field <code>.iam.v1.Gender gender = 26;</code>
     * @param int $var
     * @return $this
     */
    public function setGender($var)
    {
        GPBUtil::checkEnum($var, \Iam\V1\Gender::class);
        $this->gender = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"-" json:"region_code"
     *
     * Generated from protobuf field <code>string region_code = 27;</code>
     * @return string
     */
    public function getRegionCode()
    {
        return $this->region_code;
    }

    /**
     * &#64;gotags: gorm:"-" json:"region_code"
     *
     * Generated from protobuf field <code>string region_code = 27;</code>
     * @param string $var
     * @return $this
     */
    public function setRegionCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->region_code = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"-" json:"org"
     *
     * Generated from protobuf field <code>repeated string orgs = 28;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOrgs()
    {
        return $this->orgs;
    }

    /**
     * &#64;gotags: gorm:"-" json:"org"
     *
     * Generated from protobuf field <code>repeated string orgs = 28;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOrgs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->orgs = $arr;

        return $this;
    }

}

