<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iam/v1/hub.proto

namespace Iam\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>iam.v1.AccountStatusCode</code>
 */
class AccountStatusCode
{
    /**
     * Generated from protobuf enum <code>ACCOUNT_STATUS_NONE = 0;</code>
     */
    const ACCOUNT_STATUS_NONE = 0;
    /**
     * Generated from protobuf enum <code>NORMAL = 1;</code>
     */
    const NORMAL = 1;
    /**
     * Generated from protobuf enum <code>REMOVE_WAIT = 2;</code>
     */
    const REMOVE_WAIT = 2;
    /**
     * Generated from protobuf enum <code>REMOVE_DONE = 3;</code>
     */
    const REMOVE_DONE = 3;

    private static $valueToName = [
        self::ACCOUNT_STATUS_NONE => 'ACCOUNT_STATUS_NONE',
        self::NORMAL => 'NORMAL',
        self::REMOVE_WAIT => 'REMOVE_WAIT',
        self::REMOVE_DONE => 'REMOVE_DONE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

