<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iam/v1/hub.proto

namespace Iam\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>iam.v1.AccountsSearch</code>
 */
class AccountsSearch extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string from = 1;</code>
     */
    protected $from = '';
    /**
     * Generated from protobuf field <code>string title = 2;</code>
     */
    protected $title = '';
    /**
     * Generated from protobuf field <code>string status = 3;</code>
     */
    protected $status = '';
    /**
     * Generated from protobuf field <code>int32 gender = 4;</code>
     */
    protected $gender = 0;
    /**
     * Generated from protobuf field <code>string ringkol = 5;</code>
     */
    protected $ringkol = '';
    /**
     * Generated from protobuf field <code>int64 create_end_at = 6;</code>
     */
    protected $create_end_at = 0;
    /**
     * Generated from protobuf field <code>int64 create_start_at = 7;</code>
     */
    protected $create_start_at = 0;
    /**
     * Generated from protobuf field <code>int64 remove_end_at = 8;</code>
     */
    protected $remove_end_at = 0;
    /**
     * Generated from protobuf field <code>int64 remove_start_at = 9;</code>
     */
    protected $remove_start_at = 0;
    /**
     * Generated from protobuf field <code>int64 removed_end_at = 10;</code>
     */
    protected $removed_end_at = 0;
    /**
     * Generated from protobuf field <code>int64 removed_start_at = 11;</code>
     */
    protected $removed_start_at = 0;
    /**
     * Generated from protobuf field <code>string removed_reason = 12;</code>
     */
    protected $removed_reason = '';
    /**
     * Generated from protobuf field <code>int64 index = 13;</code>
     */
    protected $index = 0;
    /**
     * Generated from protobuf field <code>int64 size = 14;</code>
     */
    protected $size = 0;
    /**
     * Generated from protobuf field <code>string cellphone = 15;</code>
     */
    protected $cellphone = '';
    /**
     * Generated from protobuf field <code>string reason = 16;</code>
     */
    protected $reason = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $from
     *     @type string $title
     *     @type string $status
     *     @type int $gender
     *     @type string $ringkol
     *     @type int|string $create_end_at
     *     @type int|string $create_start_at
     *     @type int|string $remove_end_at
     *     @type int|string $remove_start_at
     *     @type int|string $removed_end_at
     *     @type int|string $removed_start_at
     *     @type string $removed_reason
     *     @type int|string $index
     *     @type int|string $size
     *     @type string $cellphone
     *     @type string $reason
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Iam\V1\Hub::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string from = 1;</code>
     * @return string
     */
    public function getFrom()
    {
        return $this->from;
    }

    /**
     * Generated from protobuf field <code>string from = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFrom($var)
    {
        GPBUtil::checkString($var, True);
        $this->from = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string title = 2;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 3;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 gender = 4;</code>
     * @return int
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     * Generated from protobuf field <code>int32 gender = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setGender($var)
    {
        GPBUtil::checkInt32($var);
        $this->gender = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ringkol = 5;</code>
     * @return string
     */
    public function getRingkol()
    {
        return $this->ringkol;
    }

    /**
     * Generated from protobuf field <code>string ringkol = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setRingkol($var)
    {
        GPBUtil::checkString($var, True);
        $this->ringkol = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 create_end_at = 6;</code>
     * @return int|string
     */
    public function getCreateEndAt()
    {
        return $this->create_end_at;
    }

    /**
     * Generated from protobuf field <code>int64 create_end_at = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreateEndAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->create_end_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 create_start_at = 7;</code>
     * @return int|string
     */
    public function getCreateStartAt()
    {
        return $this->create_start_at;
    }

    /**
     * Generated from protobuf field <code>int64 create_start_at = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreateStartAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->create_start_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 remove_end_at = 8;</code>
     * @return int|string
     */
    public function getRemoveEndAt()
    {
        return $this->remove_end_at;
    }

    /**
     * Generated from protobuf field <code>int64 remove_end_at = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRemoveEndAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->remove_end_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 remove_start_at = 9;</code>
     * @return int|string
     */
    public function getRemoveStartAt()
    {
        return $this->remove_start_at;
    }

    /**
     * Generated from protobuf field <code>int64 remove_start_at = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRemoveStartAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->remove_start_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 removed_end_at = 10;</code>
     * @return int|string
     */
    public function getRemovedEndAt()
    {
        return $this->removed_end_at;
    }

    /**
     * Generated from protobuf field <code>int64 removed_end_at = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRemovedEndAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->removed_end_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 removed_start_at = 11;</code>
     * @return int|string
     */
    public function getRemovedStartAt()
    {
        return $this->removed_start_at;
    }

    /**
     * Generated from protobuf field <code>int64 removed_start_at = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRemovedStartAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->removed_start_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string removed_reason = 12;</code>
     * @return string
     */
    public function getRemovedReason()
    {
        return $this->removed_reason;
    }

    /**
     * Generated from protobuf field <code>string removed_reason = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setRemovedReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->removed_reason = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 index = 13;</code>
     * @return int|string
     */
    public function getIndex()
    {
        return $this->index;
    }

    /**
     * Generated from protobuf field <code>int64 index = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIndex($var)
    {
        GPBUtil::checkInt64($var);
        $this->index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 size = 14;</code>
     * @return int|string
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * Generated from protobuf field <code>int64 size = 14;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cellphone = 15;</code>
     * @return string
     */
    public function getCellphone()
    {
        return $this->cellphone;
    }

    /**
     * Generated from protobuf field <code>string cellphone = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setCellphone($var)
    {
        GPBUtil::checkString($var, True);
        $this->cellphone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string reason = 16;</code>
     * @return string
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * Generated from protobuf field <code>string reason = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->reason = $var;

        return $this;
    }

}

