<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iam/v1/hub.proto

namespace Iam\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>iam.v1.AccountCheck</code>
 */
class AccountCheck extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string acc = 1;</code>
     */
    protected $acc = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $acc
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Iam\V1\Hub::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string acc = 1;</code>
     * @return string
     */
    public function getAcc()
    {
        return $this->acc;
    }

    /**
     * Generated from protobuf field <code>string acc = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAcc($var)
    {
        GPBUtil::checkString($var, True);
        $this->acc = $var;

        return $this;
    }

}

