<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iam/v1/hub.proto

namespace Iam\V1;

/**
 * 账号服务
 *
 * Protobuf type <code>iam.v1.Accounts</code>
 */
interface AccountsInterface
{
    /**
     * 注册账号
     *
     * Method <code>accountCreate</code>
     *
     * @param \Iam\V1\AccountRegister $request
     * @return \Iam\V1\UserAuthResp
     */
    public function accountCreate(\Iam\V1\AccountRegister $request);

    /**
     * 用户登陆加密密钥
     *
     * Method <code>userAuthAESECB</code>
     *
     * @param \Google\Protobuf\GPBEmpty $request
     * @return \Iam\V1\AESECBEncode
     */
    public function userAuthAESECB(\Google\Protobuf\GPBEmpty $request);

    /**
     * 用户登陆 v2.0
     *
     * Method <code>userAuthV2</code>
     *
     * @param \Iam\V1\UserAuth $request
     * @return \Iam\V1\UserAuthResp
     */
    public function userAuthV2(\Iam\V1\UserAuth $request);

    /**
     * 在指定设备退出当前账号（移除刷新访问凭证）
     *
     * Method <code>signOut</code>
     *
     * @param \Iam\V1\RefreshToken\Target $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function signOut(\Iam\V1\RefreshToken\Target $request);

    /**
     * 发起请求验证外部标识符，例如手机短信，发送验证码
     *
     * Method <code>verifyCodeSend</code>
     *
     * @param \Iam\V1\SendVerifyCode $request
     * @return \Iam\V1\LimitRate
     */
    public function verifyCodeSend(\Iam\V1\SendVerifyCode $request);

    /**
     * 设置或修改密码
     *
     * Method <code>setPassword</code>
     *
     * @param \Iam\V1\PasswordUpdate $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function setPassword(\Iam\V1\PasswordUpdate $request);

    /**
     * 删除密码
     *
     * Method <code>delPassword</code>
     *
     * @param \Google\Protobuf\GPBEmpty $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function delPassword(\Google\Protobuf\GPBEmpty $request);

    /**
     * PasswordExited 密码存在检查
     *
     * Method <code>passwordExited</code>
     *
     * @param \Google\Protobuf\GPBEmpty $request
     * @return \Iam\V1\DoneResp
     */
    public function passwordExited(\Google\Protobuf\GPBEmpty $request);

    /**
     * ModifyLinkID 修改另可ID
     *
     * Method <code>modifyLinkID</code>
     *
     * @param \Iam\V1\ID $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function modifyLinkID(\Iam\V1\ID $request);

    /**
     * LinkIDModifyTime 检测另可ID是否可以修改
     *
     * Method <code>linkIDModifyTime</code>
     *
     * @param \Google\Protobuf\GPBEmpty $request
     * @return \Iam\V1\TimeResp
     */
    public function linkIDModifyTime(\Google\Protobuf\GPBEmpty $request);

    /**
     * AccountExited 检测账号是否存在
     *
     * Method <code>accountExited</code>
     *
     * @param \Iam\V1\AccountCheck $request
     * @return \Iam\V1\DoneResp
     */
    public function accountExited(\Iam\V1\AccountCheck $request);

    /**
     * AccountRemoveCancel 账号注销动作撤销
     *
     * Method <code>accountRemoveCancel</code>
     *
     * @param \Google\Protobuf\GPBEmpty $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function accountRemoveCancel(\Google\Protobuf\GPBEmpty $request);

    /**
     * GenQRCode 生成二维码
     *
     * Method <code>genQRCode</code>
     *
     * @param \Iam\V1\QRGenPlatform $request
     * @return \Iam\V1\RespQRCode
     */
    public function genQRCode(\Iam\V1\QRGenPlatform $request);

    /**
     * FillQRCodeUserOpenID 回写生成的二维码用户ID
     *
     * Method <code>fillQRCodeUserOpenID</code>
     *
     * @param \Iam\V1\RespQRCodeStep $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function fillQRCodeUserOpenID(\Iam\V1\RespQRCodeStep $request);

    /**
     * GetAccounts 查询用户的账号信息
     *
     * Method <code>getAccounts</code>
     *
     * @param \Google\Protobuf\GPBEmpty $request
     * @return \Iam\V1\RespUserAccounts
     */
    public function getAccounts(\Google\Protobuf\GPBEmpty $request);

    /**
     * AccountDelete 注销用户的账号
     *
     * Method <code>accountDelete</code>
     *
     * @param \Iam\V1\AccountDeleteReq $request
     * @return \Iam\V1\AccountDeleteResp
     */
    public function accountDelete(\Iam\V1\AccountDeleteReq $request);

    /**
     * UpdateAccount 用户的账号更新
     *
     * Method <code>updateAccount</code>
     *
     * @param \Iam\V1\AccountChange $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function updateAccount(\Iam\V1\AccountChange $request);

    /**
     * VerifyCodeCheck 用户验证码有效性检查
     *
     * Method <code>verifyCodeCheck</code>
     *
     * @param \Iam\V1\VerifyCodeCheckReq $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function verifyCodeCheck(\Iam\V1\VerifyCodeCheckReq $request);

    /**
     * ForgotPassword 用户忘记密码
     *
     * Method <code>forgotPassword</code>
     *
     * @param \Iam\V1\AccountCheck $request
     * @return \Iam\V1\AccountCheckResp
     */
    public function forgotPassword(\Iam\V1\AccountCheck $request);

    /**
     * AccountDetail 用户账号详情，含身份认证信息
     *
     * Method <code>accountDetail</code>
     *
     * @param \Iam\V1\ID $request
     * @return \Iam\V1\AccountSchema
     */
    public function accountDetail(\Iam\V1\ID $request);

    /**
     * ListAccounts 用户账号查询
     *
     * Method <code>listAccounts</code>
     *
     * @param \Iam\V1\AccountsSearch $request
     * @return \Iam\V1\AccountsResp
     */
    public function listAccounts(\Iam\V1\AccountsSearch $request);

    /**
     * AccountsRegisteredCheck 批量检查用户是否注册
     *
     * Method <code>accountsRegisteredCheck</code>
     *
     * @param \Iam\V1\AccountsRegisteredCheckReq $request
     * @return \Iam\V1\AccountsRegisteredCheckResp
     */
    public function accountsRegisteredCheck(\Iam\V1\AccountsRegisteredCheckReq $request);

}

