<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iam/v1/unit.proto

namespace Iam\V1;

if (false) {
    /**
     * This class is deprecated. Use Iam\V1\Contact\PBList instead.
     * @deprecated
     */
    class Contact_List {}
}
class_exists(Contact\PBList::class);
@trigger_error('Iam\V1\Contact_List is deprecated and will be removed in the next major release. Use Iam\V1\Contact\PBList instead', E_USER_DEPRECATED);

