<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iam/v1/unit.proto

namespace Iam\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>iam.v1.Contact</code>
 */
class Contact extends \Google\Protobuf\Internal\Message
{
    /**
     * 带属地和前缀，联系人的开放标识符 + &#64; + 属地标识，比裸 ID 长
     *
     * Generated from protobuf field <code>string openid = 1 [(.validate.rules) = {</code>
     */
    protected $openid = '';
    /**
     * 对方标识符，带属地和前缀，比裸 ID 长
     *
     * Generated from protobuf field <code>string peer_id = 2 [(.validate.rules) = {</code>
     */
    protected $peer_id = '';
    /**
     * 索引，一般为首字母
     *
     * Generated from protobuf field <code>uint32 index = 3;</code>
     */
    protected $index = 0;
    /**
     * 创建时间
     *
     * Generated from protobuf field <code>int64 created = 4;</code>
     */
    protected $created = 0;
    /**
     * 确认时间
     *
     * Generated from protobuf field <code>int64 approved = 5;</code>
     */
    protected $approved = 0;
    /**
     * 扩展信息
     *
     * Generated from protobuf field <code>.iam.v1.Contact.ExtInfo ext = 6;</code>
     */
    protected $ext = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $openid
     *           带属地和前缀，联系人的开放标识符 + &#64; + 属地标识，比裸 ID 长
     *     @type string $peer_id
     *           对方标识符，带属地和前缀，比裸 ID 长
     *     @type int $index
     *           索引，一般为首字母
     *     @type int|string $created
     *           创建时间
     *     @type int|string $approved
     *           确认时间
     *     @type \Iam\V1\Contact\ExtInfo $ext
     *           扩展信息
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Iam\V1\Unit::initOnce();
        parent::__construct($data);
    }

    /**
     * 带属地和前缀，联系人的开放标识符 + &#64; + 属地标识，比裸 ID 长
     *
     * Generated from protobuf field <code>string openid = 1 [(.validate.rules) = {</code>
     * @return string
     */
    public function getOpenid()
    {
        return $this->openid;
    }

    /**
     * 带属地和前缀，联系人的开放标识符 + &#64; + 属地标识，比裸 ID 长
     *
     * Generated from protobuf field <code>string openid = 1 [(.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setOpenid($var)
    {
        GPBUtil::checkString($var, True);
        $this->openid = $var;

        return $this;
    }

    /**
     * 对方标识符，带属地和前缀，比裸 ID 长
     *
     * Generated from protobuf field <code>string peer_id = 2 [(.validate.rules) = {</code>
     * @return string
     */
    public function getPeerId()
    {
        return $this->peer_id;
    }

    /**
     * 对方标识符，带属地和前缀，比裸 ID 长
     *
     * Generated from protobuf field <code>string peer_id = 2 [(.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setPeerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->peer_id = $var;

        return $this;
    }

    /**
     * 索引，一般为首字母
     *
     * Generated from protobuf field <code>uint32 index = 3;</code>
     * @return int
     */
    public function getIndex()
    {
        return $this->index;
    }

    /**
     * 索引，一般为首字母
     *
     * Generated from protobuf field <code>uint32 index = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setIndex($var)
    {
        GPBUtil::checkUint32($var);
        $this->index = $var;

        return $this;
    }

    /**
     * 创建时间
     *
     * Generated from protobuf field <code>int64 created = 4;</code>
     * @return int|string
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * 创建时间
     *
     * Generated from protobuf field <code>int64 created = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreated($var)
    {
        GPBUtil::checkInt64($var);
        $this->created = $var;

        return $this;
    }

    /**
     * 确认时间
     *
     * Generated from protobuf field <code>int64 approved = 5;</code>
     * @return int|string
     */
    public function getApproved()
    {
        return $this->approved;
    }

    /**
     * 确认时间
     *
     * Generated from protobuf field <code>int64 approved = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setApproved($var)
    {
        GPBUtil::checkInt64($var);
        $this->approved = $var;

        return $this;
    }

    /**
     * 扩展信息
     *
     * Generated from protobuf field <code>.iam.v1.Contact.ExtInfo ext = 6;</code>
     * @return \Iam\V1\Contact\ExtInfo|null
     */
    public function getExt()
    {
        return $this->ext;
    }

    public function hasExt()
    {
        return isset($this->ext);
    }

    public function clearExt()
    {
        unset($this->ext);
    }

    /**
     * 扩展信息
     *
     * Generated from protobuf field <code>.iam.v1.Contact.ExtInfo ext = 6;</code>
     * @param \Iam\V1\Contact\ExtInfo $var
     * @return $this
     */
    public function setExt($var)
    {
        GPBUtil::checkMessage($var, \Iam\V1\Contact\ExtInfo::class);
        $this->ext = $var;

        return $this;
    }

}

