<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iam/v1/base.proto

namespace Iam\V1;

if (false) {
    /**
     * This class is deprecated. Use Iam\V1\ExchangeID\Type instead.
     * @deprecated
     */
    class ExchangeID_Type {}
}
class_exists(ExchangeID\Type::class);
@trigger_error('Iam\V1\ExchangeID_Type is deprecated and will be removed in the next major release. Use Iam\V1\ExchangeID\Type instead', E_USER_DEPRECATED);

