<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iam/v1/base.proto

namespace Iam\V1;

if (false) {
    /**
     * This class is deprecated. Use Iam\V1\ExchangeID\Request instead.
     * @deprecated
     */
    class ExchangeID_Request {}
}
class_exists(ExchangeID\Request::class);
@trigger_error('Iam\V1\ExchangeID_Request is deprecated and will be removed in the next major release. Use Iam\V1\ExchangeID\Request instead', E_USER_DEPRECATED);

