<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iam/v1/hub.proto

namespace Iam\V1;

/**
 * Protobuf type <code>iam.v1.FeedbackSrv</code>
 */
interface FeedbackSrvInterface
{
    /**
     * CreateFeedBack 意见反馈
     *
     * Method <code>createFeedback</code>
     *
     * @param \Iam\V1\FeedbackSchema $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function createFeedback(\Iam\V1\FeedbackSchema $request);

}

