<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iam/v1/base.proto

namespace Iam\V1;

if (false) {
    /**
     * This class is deprecated. Use Iam\V1\Filter\Group\Mode instead.
     * @deprecated
     */
    class Filter_Group_Mode {}
}
class_exists(Filter\Group\Mode::class);
@trigger_error('Iam\V1\Filter_Group_Mode is deprecated and will be removed in the next major release. Use Iam\V1\Filter\Group\Mode instead', E_USER_DEPRECATED);

