<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iam/v1/base.proto

namespace Iam\V1;

if (false) {
    /**
     * This class is deprecated. Use Iam\V1\Filter\PBMatch instead.
     * @deprecated
     */
    class Filter_Match {}
}
class_exists(Filter\PBMatch::class);
@trigger_error('Iam\V1\Filter_Match is deprecated and will be removed in the next major release. Use Iam\V1\Filter\PBMatch instead', E_USER_DEPRECATED);

