<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iam/v1/hub.proto

namespace Iam\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>iam.v1.HostSchema</code>
 */
class HostSchema extends \Google\Protobuf\Internal\Message
{
    /**
     * &#64;gotags: gorm:"primaryKey" json:"-"
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * &#64;gotags: gorm:"unique"
     *
     * Generated from protobuf field <code>string host = 2;</code>
     */
    protected $host = '';
    /**
     * 主域
     *
     * Generated from protobuf field <code>string domain = 3;</code>
     */
    protected $domain = '';
    /**
     * 安全码
     *
     * Generated from protobuf field <code>string secret = 4;</code>
     */
    protected $secret = '';
    /**
     *单元类型：tenant 租户，private 私有部署, public 公有部署
     *
     * Generated from protobuf field <code>.iam.v1.HostSchema.Type type = 5;</code>
     */
    protected $type = 0;
    /**
     * &#64;gotags: gorm:"serializer:json"
     *
     * Generated from protobuf field <code>string api = 6;</code>
     */
    protected $api = '';
    /**
     * &#64;gotags: gorm:"serializer:json"
     *
     * Generated from protobuf field <code>string imi = 7;</code>
     */
    protected $imi = '';
    /**
     * &#64;gotags: gorm:"serializer:json"
     *
     * Generated from protobuf field <code>string rai = 8;</code>
     */
    protected $rai = '';
    /**
     * &#64;gotags: gorm:"serializer:json"
     *
     * Generated from protobuf field <code>string sei = 9;</code>
     */
    protected $sei = '';
    /**
     * &#64;gotags: gorm:"serializer:json"
     *
     * Generated from protobuf field <code>string ip = 10;</code>
     */
    protected $ip = '';
    /**
     *启用时间戳，<=0 未启用，如果 > 0 则仅在时间戳到达后有效
     *
     * Generated from protobuf field <code>int64 enabled = 11;</code>
     */
    protected $enabled = 0;
    /**
     *禁用时间戳，<=0 表示未禁用，如果 > 0 则在时间戳到达后失效
     *
     * Generated from protobuf field <code>int64 disabled = 12;</code>
     */
    protected $disabled = 0;
    /**
     * &#64;gotags: gorm:"autoCreateTime"
     *
     * Generated from protobuf field <code>int64 created = 13;</code>
     */
    protected $created = 0;
    /**
     * &#64;gotags: gorm:"autoUpdateTime"
     *
     * Generated from protobuf field <code>int64 updated = 14;</code>
     */
    protected $updated = 0;
    /**
     *专属组织代码
     *
     * Generated from protobuf field <code>string owner = 15;</code>
     */
    protected $owner = '';
    /**
     *名称，如果是私有部署，设置为运营单位的名字
     *
     * Generated from protobuf field <code>string title = 16;</code>
     */
    protected $title = '';
    /**
     *标志图片链接
     *
     * Generated from protobuf field <code>string logo = 17;</code>
     */
    protected $logo = '';
    /**
     * &#64;gotags: gorm:"serializer:json"
     *
     * Generated from protobuf field <code>string tags = 18;</code>
     */
    protected $tags = '';
    /**
     *描述
     *
     * Generated from protobuf field <code>string description = 19;</code>
     */
    protected $description = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *           &#64;gotags: gorm:"primaryKey" json:"-"
     *     @type string $host
     *           &#64;gotags: gorm:"unique"
     *     @type string $domain
     *           主域
     *     @type string $secret
     *           安全码
     *     @type int $type
     *          单元类型：tenant 租户，private 私有部署, public 公有部署
     *     @type string $api
     *           &#64;gotags: gorm:"serializer:json"
     *     @type string $imi
     *           &#64;gotags: gorm:"serializer:json"
     *     @type string $rai
     *           &#64;gotags: gorm:"serializer:json"
     *     @type string $sei
     *           &#64;gotags: gorm:"serializer:json"
     *     @type string $ip
     *           &#64;gotags: gorm:"serializer:json"
     *     @type int|string $enabled
     *          启用时间戳，<=0 未启用，如果 > 0 则仅在时间戳到达后有效
     *     @type int|string $disabled
     *          禁用时间戳，<=0 表示未禁用，如果 > 0 则在时间戳到达后失效
     *     @type int|string $created
     *           &#64;gotags: gorm:"autoCreateTime"
     *     @type int|string $updated
     *           &#64;gotags: gorm:"autoUpdateTime"
     *     @type string $owner
     *          专属组织代码
     *     @type string $title
     *          名称，如果是私有部署，设置为运营单位的名字
     *     @type string $logo
     *          标志图片链接
     *     @type string $tags
     *           &#64;gotags: gorm:"serializer:json"
     *     @type string $description
     *          描述
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Iam\V1\Hub::initOnce();
        parent::__construct($data);
    }

    /**
     * &#64;gotags: gorm:"primaryKey" json:"-"
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * &#64;gotags: gorm:"primaryKey" json:"-"
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"unique"
     *
     * Generated from protobuf field <code>string host = 2;</code>
     * @return string
     */
    public function getHost()
    {
        return $this->host;
    }

    /**
     * &#64;gotags: gorm:"unique"
     *
     * Generated from protobuf field <code>string host = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->host = $var;

        return $this;
    }

    /**
     * 主域
     *
     * Generated from protobuf field <code>string domain = 3;</code>
     * @return string
     */
    public function getDomain()
    {
        return $this->domain;
    }

    /**
     * 主域
     *
     * Generated from protobuf field <code>string domain = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDomain($var)
    {
        GPBUtil::checkString($var, True);
        $this->domain = $var;

        return $this;
    }

    /**
     * 安全码
     *
     * Generated from protobuf field <code>string secret = 4;</code>
     * @return string
     */
    public function getSecret()
    {
        return $this->secret;
    }

    /**
     * 安全码
     *
     * Generated from protobuf field <code>string secret = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSecret($var)
    {
        GPBUtil::checkString($var, True);
        $this->secret = $var;

        return $this;
    }

    /**
     *单元类型：tenant 租户，private 私有部署, public 公有部署
     *
     * Generated from protobuf field <code>.iam.v1.HostSchema.Type type = 5;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     *单元类型：tenant 租户，private 私有部署, public 公有部署
     *
     * Generated from protobuf field <code>.iam.v1.HostSchema.Type type = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Iam\V1\HostSchema\Type::class);
        $this->type = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"serializer:json"
     *
     * Generated from protobuf field <code>string api = 6;</code>
     * @return string
     */
    public function getApi()
    {
        return $this->api;
    }

    /**
     * &#64;gotags: gorm:"serializer:json"
     *
     * Generated from protobuf field <code>string api = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setApi($var)
    {
        GPBUtil::checkString($var, True);
        $this->api = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"serializer:json"
     *
     * Generated from protobuf field <code>string imi = 7;</code>
     * @return string
     */
    public function getImi()
    {
        return $this->imi;
    }

    /**
     * &#64;gotags: gorm:"serializer:json"
     *
     * Generated from protobuf field <code>string imi = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setImi($var)
    {
        GPBUtil::checkString($var, True);
        $this->imi = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"serializer:json"
     *
     * Generated from protobuf field <code>string rai = 8;</code>
     * @return string
     */
    public function getRai()
    {
        return $this->rai;
    }

    /**
     * &#64;gotags: gorm:"serializer:json"
     *
     * Generated from protobuf field <code>string rai = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setRai($var)
    {
        GPBUtil::checkString($var, True);
        $this->rai = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"serializer:json"
     *
     * Generated from protobuf field <code>string sei = 9;</code>
     * @return string
     */
    public function getSei()
    {
        return $this->sei;
    }

    /**
     * &#64;gotags: gorm:"serializer:json"
     *
     * Generated from protobuf field <code>string sei = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setSei($var)
    {
        GPBUtil::checkString($var, True);
        $this->sei = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"serializer:json"
     *
     * Generated from protobuf field <code>string ip = 10;</code>
     * @return string
     */
    public function getIp()
    {
        return $this->ip;
    }

    /**
     * &#64;gotags: gorm:"serializer:json"
     *
     * Generated from protobuf field <code>string ip = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->ip = $var;

        return $this;
    }

    /**
     *启用时间戳，<=0 未启用，如果 > 0 则仅在时间戳到达后有效
     *
     * Generated from protobuf field <code>int64 enabled = 11;</code>
     * @return int|string
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     *启用时间戳，<=0 未启用，如果 > 0 则仅在时间戳到达后有效
     *
     * Generated from protobuf field <code>int64 enabled = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEnabled($var)
    {
        GPBUtil::checkInt64($var);
        $this->enabled = $var;

        return $this;
    }

    /**
     *禁用时间戳，<=0 表示未禁用，如果 > 0 则在时间戳到达后失效
     *
     * Generated from protobuf field <code>int64 disabled = 12;</code>
     * @return int|string
     */
    public function getDisabled()
    {
        return $this->disabled;
    }

    /**
     *禁用时间戳，<=0 表示未禁用，如果 > 0 则在时间戳到达后失效
     *
     * Generated from protobuf field <code>int64 disabled = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDisabled($var)
    {
        GPBUtil::checkInt64($var);
        $this->disabled = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"autoCreateTime"
     *
     * Generated from protobuf field <code>int64 created = 13;</code>
     * @return int|string
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * &#64;gotags: gorm:"autoCreateTime"
     *
     * Generated from protobuf field <code>int64 created = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreated($var)
    {
        GPBUtil::checkInt64($var);
        $this->created = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"autoUpdateTime"
     *
     * Generated from protobuf field <code>int64 updated = 14;</code>
     * @return int|string
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * &#64;gotags: gorm:"autoUpdateTime"
     *
     * Generated from protobuf field <code>int64 updated = 14;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpdated($var)
    {
        GPBUtil::checkInt64($var);
        $this->updated = $var;

        return $this;
    }

    /**
     *专属组织代码
     *
     * Generated from protobuf field <code>string owner = 15;</code>
     * @return string
     */
    public function getOwner()
    {
        return $this->owner;
    }

    /**
     *专属组织代码
     *
     * Generated from protobuf field <code>string owner = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setOwner($var)
    {
        GPBUtil::checkString($var, True);
        $this->owner = $var;

        return $this;
    }

    /**
     *名称，如果是私有部署，设置为运营单位的名字
     *
     * Generated from protobuf field <code>string title = 16;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     *名称，如果是私有部署，设置为运营单位的名字
     *
     * Generated from protobuf field <code>string title = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     *标志图片链接
     *
     * Generated from protobuf field <code>string logo = 17;</code>
     * @return string
     */
    public function getLogo()
    {
        return $this->logo;
    }

    /**
     *标志图片链接
     *
     * Generated from protobuf field <code>string logo = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setLogo($var)
    {
        GPBUtil::checkString($var, True);
        $this->logo = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"serializer:json"
     *
     * Generated from protobuf field <code>string tags = 18;</code>
     * @return string
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * &#64;gotags: gorm:"serializer:json"
     *
     * Generated from protobuf field <code>string tags = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setTags($var)
    {
        GPBUtil::checkString($var, True);
        $this->tags = $var;

        return $this;
    }

    /**
     *描述
     *
     * Generated from protobuf field <code>string description = 19;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     *描述
     *
     * Generated from protobuf field <code>string description = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

}

