<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iam/v1/Base.proto

namespace Iam\V1;

if (false) {
    /**
     * This class is deprecated. Use Iam\V1\LocalID\PBList instead.
     * @deprecated
     */
    class LocalID_List {}
}
class_exists(LocalID\PBList::class);
@trigger_error('Iam\V1\LocalID_List is deprecated and will be removed in the next major release. Use Iam\V1\LocalID\PBList instead', E_USER_DEPRECATED);

