<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iam/v1/base.proto

namespace Iam\V1;

if (false) {
    /**
     * This class is deprecated. Use Iam\V1\OrderBy\PBList instead.
     * @deprecated
     */
    class OrderBy_List {}
}
class_exists(OrderBy\PBList::class);
@trigger_error('Iam\V1\OrderBy_List is deprecated and will be removed in the next major release. Use Iam\V1\OrderBy\PBList instead', E_USER_DEPRECATED);

