<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iam/v1/base.proto

namespace Iam\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 保护规则
 *
 * Generated from protobuf message <code>iam.v1.ProtectedRule</code>
 */
class ProtectedRule extends \Google\Protobuf\Internal\Message
{
    /**
     * 定义保护区
     *
     * Generated from protobuf field <code>.iam.v1.ProtectedZone zone = 1;</code>
     */
    protected $zone = 0;
    /**
     * 定义保护类型
     *
     * Generated from protobuf field <code>.iam.v1.ProtectedKind kind = 2;</code>
     */
    protected $kind = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $zone
     *           定义保护区
     *     @type int $kind
     *           定义保护类型
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Iam\V1\Base::initOnce();
        parent::__construct($data);
    }

    /**
     * 定义保护区
     *
     * Generated from protobuf field <code>.iam.v1.ProtectedZone zone = 1;</code>
     * @return int
     */
    public function getZone()
    {
        return $this->zone;
    }

    /**
     * 定义保护区
     *
     * Generated from protobuf field <code>.iam.v1.ProtectedZone zone = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setZone($var)
    {
        GPBUtil::checkEnum($var, \Iam\V1\ProtectedZone::class);
        $this->zone = $var;

        return $this;
    }

    /**
     * 定义保护类型
     *
     * Generated from protobuf field <code>.iam.v1.ProtectedKind kind = 2;</code>
     * @return int
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     * 定义保护类型
     *
     * Generated from protobuf field <code>.iam.v1.ProtectedKind kind = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setKind($var)
    {
        GPBUtil::checkEnum($var, \Iam\V1\ProtectedKind::class);
        $this->kind = $var;

        return $this;
    }

}

