<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iam/v1/hub.proto

namespace Iam\v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>iam.v1.PsnInfo</code>
 */
class PsnInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * &#64;gotags: json:"psnName"
     *
     * Generated from protobuf field <code>string psnName = 1;</code>
     */
    protected $psnName = '';
    /**
     * &#64;gotags: json:"psnNationality"
     *
     * Generated from protobuf field <code>string psnNationality = 2;</code>
     */
    protected $psnNationality = '';
    /**
     * &#64;gotags: json:"psnIDCardNum"
     *
     * Generated from protobuf field <code>string psnIDCardNum = 3;</code>
     */
    protected $psnIDCardNum = '';
    /**
     * &#64;gotags: json:"psnIDCardType"
     *
     * Generated from protobuf field <code>string psnIDCardType = 4;</code>
     */
    protected $psnIDCardType = '';
    /**
     * &#64;gotags: json:"bankCardNum"
     *
     * Generated from protobuf field <code>string bankCardNum = 5;</code>
     */
    protected $bankCardNum = '';
    /**
     * &#64;gotags: json:"psnMobile"
     *
     * Generated from protobuf field <code>string psnMobile = 6;</code>
     */
    protected $psnMobile = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $psnName
     *           &#64;gotags: json:"psnName"
     *     @type string $psnNationality
     *           &#64;gotags: json:"psnNationality"
     *     @type string $psnIDCardNum
     *           &#64;gotags: json:"psnIDCardNum"
     *     @type string $psnIDCardType
     *           &#64;gotags: json:"psnIDCardType"
     *     @type string $bankCardNum
     *           &#64;gotags: json:"bankCardNum"
     *     @type string $psnMobile
     *           &#64;gotags: json:"psnMobile"
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Iam\v1\Hub::initOnce();
        parent::__construct($data);
    }

    /**
     * &#64;gotags: json:"psnName"
     *
     * Generated from protobuf field <code>string psnName = 1;</code>
     * @return string
     */
    public function getPsnName()
    {
        return $this->psnName;
    }

    /**
     * &#64;gotags: json:"psnName"
     *
     * Generated from protobuf field <code>string psnName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPsnName($var)
    {
        GPBUtil::checkString($var, True);
        $this->psnName = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"psnNationality"
     *
     * Generated from protobuf field <code>string psnNationality = 2;</code>
     * @return string
     */
    public function getPsnNationality()
    {
        return $this->psnNationality;
    }

    /**
     * &#64;gotags: json:"psnNationality"
     *
     * Generated from protobuf field <code>string psnNationality = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPsnNationality($var)
    {
        GPBUtil::checkString($var, True);
        $this->psnNationality = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"psnIDCardNum"
     *
     * Generated from protobuf field <code>string psnIDCardNum = 3;</code>
     * @return string
     */
    public function getPsnIDCardNum()
    {
        return $this->psnIDCardNum;
    }

    /**
     * &#64;gotags: json:"psnIDCardNum"
     *
     * Generated from protobuf field <code>string psnIDCardNum = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPsnIDCardNum($var)
    {
        GPBUtil::checkString($var, True);
        $this->psnIDCardNum = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"psnIDCardType"
     *
     * Generated from protobuf field <code>string psnIDCardType = 4;</code>
     * @return string
     */
    public function getPsnIDCardType()
    {
        return $this->psnIDCardType;
    }

    /**
     * &#64;gotags: json:"psnIDCardType"
     *
     * Generated from protobuf field <code>string psnIDCardType = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPsnIDCardType($var)
    {
        GPBUtil::checkString($var, True);
        $this->psnIDCardType = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"bankCardNum"
     *
     * Generated from protobuf field <code>string bankCardNum = 5;</code>
     * @return string
     */
    public function getBankCardNum()
    {
        return $this->bankCardNum;
    }

    /**
     * &#64;gotags: json:"bankCardNum"
     *
     * Generated from protobuf field <code>string bankCardNum = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setBankCardNum($var)
    {
        GPBUtil::checkString($var, True);
        $this->bankCardNum = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"psnMobile"
     *
     * Generated from protobuf field <code>string psnMobile = 6;</code>
     * @return string
     */
    public function getPsnMobile()
    {
        return $this->psnMobile;
    }

    /**
     * &#64;gotags: json:"psnMobile"
     *
     * Generated from protobuf field <code>string psnMobile = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPsnMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->psnMobile = $var;

        return $this;
    }

}

