<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iam/v1/hub.proto

namespace Iam\v1;

use UnexpectedValueException;

/**
 * Protobuf type <code>iam.v1.QRCodeStep</code>
 */
class QRCodeStep
{
    /**
     * Generated from protobuf enum <code>SCAN = 0;</code>
     */
    const SCAN = 0;
    /**
     * Generated from protobuf enum <code>VERIFY = 1;</code>
     */
    const VERIFY = 1;
    /**
     * Generated from protobuf enum <code>CANCEL = 2;</code>
     */
    const CANCEL = 2;

    private static $valueToName = [
        self::SCAN => 'SCAN',
        self::VERIFY => 'VERIFY',
        self::CANCEL => 'CANCEL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

