<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iam/v1/hub.proto

namespace Iam\v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>iam.v1.RedirectConfig</code>
 */
class RedirectConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * &#64;gotags: json:"redirectUrl"
     *
     * Generated from protobuf field <code>string redirect_url = 1;</code>
     */
    protected $redirect_url = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $redirect_url
     *           &#64;gotags: json:"redirectUrl"
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Iam\v1\Hub::initOnce();
        parent::__construct($data);
    }

    /**
     * &#64;gotags: json:"redirectUrl"
     *
     * Generated from protobuf field <code>string redirect_url = 1;</code>
     * @return string
     */
    public function getRedirectUrl()
    {
        return $this->redirect_url;
    }

    /**
     * &#64;gotags: json:"redirectUrl"
     *
     * Generated from protobuf field <code>string redirect_url = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRedirectUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->redirect_url = $var;

        return $this;
    }

}

