<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iam/v1/hub.proto

namespace Iam\V1;

if (false) {
    /**
     * This class is deprecated. Use Iam\V1\RefreshToken\Request instead.
     * @deprecated
     */
    class RefreshToken_Request {}
}
class_exists(RefreshToken\Request::class);
@trigger_error('Iam\V1\RefreshToken_Request is deprecated and will be removed in the next major release. Use Iam\V1\RefreshToken\Request instead', E_USER_DEPRECATED);

