<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iam/v1/hub.proto

namespace Iam\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 安全问答
 *
 * Generated from protobuf message <code>iam.v1.SQAs</code>
 */
class SQAs extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .iam.v1.SQAs.Item items = 1 [(.validate.rules) = {</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Iam\V1\SQAs\Item[]|\Google\Protobuf\Internal\RepeatedField $items
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Iam\V1\Hub::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .iam.v1.SQAs.Item items = 1 [(.validate.rules) = {</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .iam.v1.SQAs.Item items = 1 [(.validate.rules) = {</code>
     * @param \Iam\V1\SQAs\Item[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Iam\V1\SQAs\Item::class);
        $this->items = $arr;

        return $this;
    }

}

