<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iam/v1/hub.proto

namespace Iam\V1;

if (false) {
    /**
     * This class is deprecated. Use Iam\V1\SQAs\Item instead.
     * @deprecated
     */
    class SQAs_Item {}
}
class_exists(SQAs\Item::class);
@trigger_error('Iam\V1\SQAs_Item is deprecated and will be removed in the next major release. Use Iam\V1\SQAs\Item instead', E_USER_DEPRECATED);

