<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iam/v1/unit.proto

namespace Iam\V1\Contact;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 扩展信息
 *
 * Generated from protobuf message <code>iam.v1.Contact.ExtInfo</code>
 */
class ExtInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * 联系人的备注名
     *
     * Generated from protobuf field <code>string label = 2 [(.validate.rules) = {</code>
     */
    protected $label = '';
    /**
     * 添加关系的来源
     *
     * Generated from protobuf field <code>string source = 3 [(.validate.rules) = {</code>
     */
    protected $source = '';
    /**
     * 联系人的标签，一维数组
     *
     * Generated from protobuf field <code>repeated string tags = 4;</code>
     */
    private $tags;
    /**
     * 备注
     *
     * Generated from protobuf field <code>string comment = 5;</code>
     */
    protected $comment = '';
    /**
     * 其它扩展信息
     *
     * Generated from protobuf field <code>repeated .iam.v1.Ext.Item items = 6;</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type string $label
     *           联系人的备注名
     *     @type string $source
     *           添加关系的来源
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $tags
     *           联系人的标签，一维数组
     *     @type string $comment
     *           备注
     *     @type \Iam\V1\Ext\Item[]|\Google\Protobuf\Internal\RepeatedField $items
     *           其它扩展信息
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Iam\V1\Unit::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * 联系人的备注名
     *
     * Generated from protobuf field <code>string label = 2 [(.validate.rules) = {</code>
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * 联系人的备注名
     *
     * Generated from protobuf field <code>string label = 2 [(.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setLabel($var)
    {
        GPBUtil::checkString($var, True);
        $this->label = $var;

        return $this;
    }

    /**
     * 添加关系的来源
     *
     * Generated from protobuf field <code>string source = 3 [(.validate.rules) = {</code>
     * @return string
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * 添加关系的来源
     *
     * Generated from protobuf field <code>string source = 3 [(.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->source = $var;

        return $this;
    }

    /**
     * 联系人的标签，一维数组
     *
     * Generated from protobuf field <code>repeated string tags = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * 联系人的标签，一维数组
     *
     * Generated from protobuf field <code>repeated string tags = 4;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tags = $arr;

        return $this;
    }

    /**
     * 备注
     *
     * Generated from protobuf field <code>string comment = 5;</code>
     * @return string
     */
    public function getComment()
    {
        return $this->comment;
    }

    /**
     * 备注
     *
     * Generated from protobuf field <code>string comment = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setComment($var)
    {
        GPBUtil::checkString($var, True);
        $this->comment = $var;

        return $this;
    }

    /**
     * 其它扩展信息
     *
     * Generated from protobuf field <code>repeated .iam.v1.Ext.Item items = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * 其它扩展信息
     *
     * Generated from protobuf field <code>repeated .iam.v1.Ext.Item items = 6;</code>
     * @param \Iam\V1\Ext\Item[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Iam\V1\Ext\Item::class);
        $this->items = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ExtInfo::class, \Iam\V1\Contact_ExtInfo::class);

