<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iam/v1/Base.proto

namespace Iam\V1\ExchangeID;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 交换标识符应答
 *
 * Generated from protobuf message <code>iam.v1.ExchangeID.Acked</code>
 */
class Acked extends \Google\Protobuf\Internal\Message
{
    /**
     * 应答代码
     *
     * Generated from protobuf field <code>string code = 1;</code>
     */
    protected $code = '';
    /**
     * 用户或系统授权的范围
     *
     * Generated from protobuf field <code>repeated string scopes = 2;</code>
     */
    private $scopes;
    /**
     * 任意其它数据
     *
     * Generated from protobuf field <code>.google.protobuf.Any any = 3;</code>
     */
    protected $any = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $code
     *           应答代码
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $scopes
     *           用户或系统授权的范围
     *     @type \Google\Protobuf\Any $any
     *           任意其它数据
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Iam\V1\Base::initOnce();
        parent::__construct($data);
    }

    /**
     * 应答代码
     *
     * Generated from protobuf field <code>string code = 1;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * 应答代码
     *
     * Generated from protobuf field <code>string code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * 用户或系统授权的范围
     *
     * Generated from protobuf field <code>repeated string scopes = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getScopes()
    {
        return $this->scopes;
    }

    /**
     * 用户或系统授权的范围
     *
     * Generated from protobuf field <code>repeated string scopes = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setScopes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->scopes = $arr;

        return $this;
    }

    /**
     * 任意其它数据
     *
     * Generated from protobuf field <code>.google.protobuf.Any any = 3;</code>
     * @return \Google\Protobuf\Any|null
     */
    public function getAny()
    {
        return $this->any;
    }

    public function hasAny()
    {
        return isset($this->any);
    }

    public function clearAny()
    {
        unset($this->any);
    }

    /**
     * 任意其它数据
     *
     * Generated from protobuf field <code>.google.protobuf.Any any = 3;</code>
     * @param \Google\Protobuf\Any $var
     * @return $this
     */
    public function setAny($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Any::class);
        $this->any = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Acked::class, \Iam\V1\ExchangeID_Acked::class);

