<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iam/v1/unit.proto

namespace Iam\V1\Profile;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 个人档案列表
 *
 * Generated from protobuf message <code>iam.v1.Profile.List</code>
 */
class PBList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .iam.v1.Profile items = 1;</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Iam\V1\Profile[]|\Google\Protobuf\Internal\RepeatedField $items
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Iam\V1\Unit::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .iam.v1.Profile items = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .iam.v1.Profile items = 1;</code>
     * @param \Iam\V1\Profile[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Iam\V1\Profile::class);
        $this->items = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(PBList::class, \Iam\V1\Profile_List::class);

