<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/sync.proto

namespace Im\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>im.v1.Apply</code>
 */
class Apply extends \Google\Protobuf\Internal\Message
{
    /**
     * &#64;gotags: gorm:"primaryKey" json:"-"
     *
     * Generated from protobuf field <code>int64 lid = 1;</code>
     */
    protected $lid = 0;
    /**
     * &#64;gotags: json:"openid"
     *
     * Generated from protobuf field <code>string openid = 2;</code>
     */
    protected $openid = '';
    /**
     * &#64;gotags: json:"applicant"
     *
     * Generated from protobuf field <code>string applicant = 3;</code>
     */
    protected $applicant = '';
    /**
     * &#64;gotags: gorm:"serializer:json" json:"handler"
     *
     * Generated from protobuf field <code>repeated string handler = 4;</code>
     */
    private $handler;
    /**
     * &#64;gotags: json:"typ"
     *
     * Generated from protobuf field <code>int32 typ = 5;</code>
     */
    protected $typ = 0;
    /**
     * &#64;gotags: gorm:"serializer:json" json:"members"
     *
     * Generated from protobuf field <code>repeated .im.v1.Member members = 6;</code>
     */
    private $members;
    /**
     * &#64;gotags: json:"status"
     *
     * Generated from protobuf field <code>string status = 7;</code>
     */
    protected $status = '';
    /**
     * &#64;gotags: json:"create_at"
     *
     * Generated from protobuf field <code>int64 create_at = 8;</code>
     */
    protected $create_at = 0;
    /**
     * &#64;gotags: json:"update_at"
     *
     * Generated from protobuf field <code>int64 update_at = 9;</code>
     */
    protected $update_at = 0;
    /**
     * &#64;gotags: json:"delete_at"
     *
     * Generated from protobuf field <code>int64 delete_at = 10;</code>
     */
    protected $delete_at = 0;
    /**
     * &#64;gotags: gorm:"serializer:json" json:"card_ids"
     *
     * Generated from protobuf field <code>repeated string card_ids = 11;</code>
     */
    private $card_ids;
    /**
     * &#64;gotags: json:"gid"
     *
     * Generated from protobuf field <code>string gid = 12;</code>
     */
    protected $gid = '';
    /**
     * &#64;gotags: json:"content"
     *
     * Generated from protobuf field <code>string content = 13;</code>
     */
    protected $content = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $lid
     *           &#64;gotags: gorm:"primaryKey" json:"-"
     *     @type string $openid
     *           &#64;gotags: json:"openid"
     *     @type string $applicant
     *           &#64;gotags: json:"applicant"
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $handler
     *           &#64;gotags: gorm:"serializer:json" json:"handler"
     *     @type int $typ
     *           &#64;gotags: json:"typ"
     *     @type \Im\V1\Member[]|\Google\Protobuf\Internal\RepeatedField $members
     *           &#64;gotags: gorm:"serializer:json" json:"members"
     *     @type string $status
     *           &#64;gotags: json:"status"
     *     @type int|string $create_at
     *           &#64;gotags: json:"create_at"
     *     @type int|string $update_at
     *           &#64;gotags: json:"update_at"
     *     @type int|string $delete_at
     *           &#64;gotags: json:"delete_at"
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $card_ids
     *           &#64;gotags: gorm:"serializer:json" json:"card_ids"
     *     @type string $gid
     *           &#64;gotags: json:"gid"
     *     @type string $content
     *           &#64;gotags: json:"content"
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Im\V1\Sync::initOnce();
        parent::__construct($data);
    }

    /**
     * &#64;gotags: gorm:"primaryKey" json:"-"
     *
     * Generated from protobuf field <code>int64 lid = 1;</code>
     * @return int|string
     */
    public function getLid()
    {
        return $this->lid;
    }

    /**
     * &#64;gotags: gorm:"primaryKey" json:"-"
     *
     * Generated from protobuf field <code>int64 lid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLid($var)
    {
        GPBUtil::checkInt64($var);
        $this->lid = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"openid"
     *
     * Generated from protobuf field <code>string openid = 2;</code>
     * @return string
     */
    public function getOpenid()
    {
        return $this->openid;
    }

    /**
     * &#64;gotags: json:"openid"
     *
     * Generated from protobuf field <code>string openid = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOpenid($var)
    {
        GPBUtil::checkString($var, True);
        $this->openid = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"applicant"
     *
     * Generated from protobuf field <code>string applicant = 3;</code>
     * @return string
     */
    public function getApplicant()
    {
        return $this->applicant;
    }

    /**
     * &#64;gotags: json:"applicant"
     *
     * Generated from protobuf field <code>string applicant = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setApplicant($var)
    {
        GPBUtil::checkString($var, True);
        $this->applicant = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"serializer:json" json:"handler"
     *
     * Generated from protobuf field <code>repeated string handler = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHandler()
    {
        return $this->handler;
    }

    /**
     * &#64;gotags: gorm:"serializer:json" json:"handler"
     *
     * Generated from protobuf field <code>repeated string handler = 4;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHandler($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->handler = $arr;

        return $this;
    }

    /**
     * &#64;gotags: json:"typ"
     *
     * Generated from protobuf field <code>int32 typ = 5;</code>
     * @return int
     */
    public function getTyp()
    {
        return $this->typ;
    }

    /**
     * &#64;gotags: json:"typ"
     *
     * Generated from protobuf field <code>int32 typ = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setTyp($var)
    {
        GPBUtil::checkInt32($var);
        $this->typ = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"serializer:json" json:"members"
     *
     * Generated from protobuf field <code>repeated .im.v1.Member members = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMembers()
    {
        return $this->members;
    }

    /**
     * &#64;gotags: gorm:"serializer:json" json:"members"
     *
     * Generated from protobuf field <code>repeated .im.v1.Member members = 6;</code>
     * @param \Im\V1\Member[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMembers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Im\V1\Member::class);
        $this->members = $arr;

        return $this;
    }

    /**
     * &#64;gotags: json:"status"
     *
     * Generated from protobuf field <code>string status = 7;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * &#64;gotags: json:"status"
     *
     * Generated from protobuf field <code>string status = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"create_at"
     *
     * Generated from protobuf field <code>int64 create_at = 8;</code>
     * @return int|string
     */
    public function getCreateAt()
    {
        return $this->create_at;
    }

    /**
     * &#64;gotags: json:"create_at"
     *
     * Generated from protobuf field <code>int64 create_at = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreateAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->create_at = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"update_at"
     *
     * Generated from protobuf field <code>int64 update_at = 9;</code>
     * @return int|string
     */
    public function getUpdateAt()
    {
        return $this->update_at;
    }

    /**
     * &#64;gotags: json:"update_at"
     *
     * Generated from protobuf field <code>int64 update_at = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpdateAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->update_at = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"delete_at"
     *
     * Generated from protobuf field <code>int64 delete_at = 10;</code>
     * @return int|string
     */
    public function getDeleteAt()
    {
        return $this->delete_at;
    }

    /**
     * &#64;gotags: json:"delete_at"
     *
     * Generated from protobuf field <code>int64 delete_at = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDeleteAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->delete_at = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"serializer:json" json:"card_ids"
     *
     * Generated from protobuf field <code>repeated string card_ids = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCardIds()
    {
        return $this->card_ids;
    }

    /**
     * &#64;gotags: gorm:"serializer:json" json:"card_ids"
     *
     * Generated from protobuf field <code>repeated string card_ids = 11;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCardIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->card_ids = $arr;

        return $this;
    }

    /**
     * &#64;gotags: json:"gid"
     *
     * Generated from protobuf field <code>string gid = 12;</code>
     * @return string
     */
    public function getGid()
    {
        return $this->gid;
    }

    /**
     * &#64;gotags: json:"gid"
     *
     * Generated from protobuf field <code>string gid = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setGid($var)
    {
        GPBUtil::checkString($var, True);
        $this->gid = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"content"
     *
     * Generated from protobuf field <code>string content = 13;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * &#64;gotags: json:"content"
     *
     * Generated from protobuf field <code>string content = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;

        return $this;
    }

}

