<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/sync.proto

namespace Im\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>im.v1.BlessingWordsBatchReq</code>
 */
class BlessingWordsBatchReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string words = 1;</code>
     */
    protected $words = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $words
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Im\V1\Sync::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string words = 1;</code>
     * @return string
     */
    public function getWords()
    {
        return $this->words;
    }

    /**
     * Generated from protobuf field <code>string words = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWords($var)
    {
        GPBUtil::checkString($var, True);
        $this->words = $var;

        return $this;
    }

}

