<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/sync.proto

namespace Im\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>im.v1.MemberAddBatch</code>
 */
class MemberAddBatch extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string group = 1;</code>
     */
    protected $group = '';
    /**
     * Generated from protobuf field <code>repeated string rids = 2;</code>
     */
    private $rids;
    /**
     * Generated from protobuf field <code>repeated .im.v1.Member members = 3;</code>
     */
    private $members;
    /**
     * Generated from protobuf field <code>string op_card_id = 4;</code>
     */
    protected $op_card_id = '';
    /**
     * 是否服务端调用
     *
     * Generated from protobuf field <code>bool from_server = 5;</code>
     */
    protected $from_server = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $group
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $rids
     *     @type \Im\V1\Member[]|\Google\Protobuf\Internal\RepeatedField $members
     *     @type string $op_card_id
     *     @type bool $from_server
     *           是否服务端调用
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Im\V1\Sync::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string group = 1;</code>
     * @return string
     */
    public function getGroup()
    {
        return $this->group;
    }

    /**
     * Generated from protobuf field <code>string group = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setGroup($var)
    {
        GPBUtil::checkString($var, True);
        $this->group = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string rids = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRids()
    {
        return $this->rids;
    }

    /**
     * Generated from protobuf field <code>repeated string rids = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRids($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->rids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .im.v1.Member members = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMembers()
    {
        return $this->members;
    }

    /**
     * Generated from protobuf field <code>repeated .im.v1.Member members = 3;</code>
     * @param \Im\V1\Member[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMembers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Im\V1\Member::class);
        $this->members = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string op_card_id = 4;</code>
     * @return string
     */
    public function getOpCardId()
    {
        return $this->op_card_id;
    }

    /**
     * Generated from protobuf field <code>string op_card_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setOpCardId($var)
    {
        GPBUtil::checkString($var, True);
        $this->op_card_id = $var;

        return $this;
    }

    /**
     * 是否服务端调用
     *
     * Generated from protobuf field <code>bool from_server = 5;</code>
     * @return bool
     */
    public function getFromServer()
    {
        return $this->from_server;
    }

    /**
     * 是否服务端调用
     *
     * Generated from protobuf field <code>bool from_server = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setFromServer($var)
    {
        GPBUtil::checkBool($var);
        $this->from_server = $var;

        return $this;
    }

}

