<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/sync.proto

namespace Im\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>im.v1.VoiceStreamRecordOutputCallback</code>
 */
class VoiceStreamRecordOutputCallback extends \Google\Protobuf\Internal\Message
{
    /**
     * 音频文件地址
     *
     * Generated from protobuf field <code>string file_url = 1;</code>
     */
    protected $file_url = '';
    /**
     * 音频文件大小
     *
     * Generated from protobuf field <code>int64 file_size = 2;</code>
     */
    protected $file_size = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $file_url
     *           音频文件地址
     *     @type int|string $file_size
     *           音频文件大小
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Im\V1\Sync::initOnce();
        parent::__construct($data);
    }

    /**
     * 音频文件地址
     *
     * Generated from protobuf field <code>string file_url = 1;</code>
     * @return string
     */
    public function getFileUrl()
    {
        return $this->file_url;
    }

    /**
     * 音频文件地址
     *
     * Generated from protobuf field <code>string file_url = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFileUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->file_url = $var;

        return $this;
    }

    /**
     * 音频文件大小
     *
     * Generated from protobuf field <code>int64 file_size = 2;</code>
     * @return int|string
     */
    public function getFileSize()
    {
        return $this->file_size;
    }

    /**
     * 音频文件大小
     *
     * Generated from protobuf field <code>int64 file_size = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFileSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->file_size = $var;

        return $this;
    }

}

