<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/sync.proto

namespace Im\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>im.v1.VoiceStreamRecordCallback</code>
 */
class VoiceStreamRecordCallback extends \Google\Protobuf\Internal\Message
{
    /**
     * 回调事件类型
     *
     * Generated from protobuf field <code>int64 type = 1;</code>
     */
    protected $type = 0;
    /**
     * 房间ID
     *
     * Generated from protobuf field <code>string user_id = 2;</code>
     */
    protected $user_id = '';
    /**
     * 房间ID
     *
     * Generated from protobuf field <code>string room_id = 3;</code>
     */
    protected $room_id = '';
    /**
     * 录制ID
     *
     * Generated from protobuf field <code>string record_id = 4;</code>
     */
    protected $record_id = '';
    /**
     * 时间戳
     *
     * Generated from protobuf field <code>int64 timestamp = 5;</code>
     */
    protected $timestamp = 0;
    /**
     * 录制文件上传完成回调
     *
     * Generated from protobuf field <code>.im.v1.VoiceStreamRecordOutputCallback output = 6;</code>
     */
    protected $output = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $type
     *           回调事件类型
     *     @type string $user_id
     *           房间ID
     *     @type string $room_id
     *           房间ID
     *     @type string $record_id
     *           录制ID
     *     @type int|string $timestamp
     *           时间戳
     *     @type \Im\V1\VoiceStreamRecordOutputCallback $output
     *           录制文件上传完成回调
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Im\V1\Sync::initOnce();
        parent::__construct($data);
    }

    /**
     * 回调事件类型
     *
     * Generated from protobuf field <code>int64 type = 1;</code>
     * @return int|string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * 回调事件类型
     *
     * Generated from protobuf field <code>int64 type = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt64($var);
        $this->type = $var;

        return $this;
    }

    /**
     * 房间ID
     *
     * Generated from protobuf field <code>string user_id = 2;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * 房间ID
     *
     * Generated from protobuf field <code>string user_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     * 房间ID
     *
     * Generated from protobuf field <code>string room_id = 3;</code>
     * @return string
     */
    public function getRoomId()
    {
        return $this->room_id;
    }

    /**
     * 房间ID
     *
     * Generated from protobuf field <code>string room_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRoomId($var)
    {
        GPBUtil::checkString($var, True);
        $this->room_id = $var;

        return $this;
    }

    /**
     * 录制ID
     *
     * Generated from protobuf field <code>string record_id = 4;</code>
     * @return string
     */
    public function getRecordId()
    {
        return $this->record_id;
    }

    /**
     * 录制ID
     *
     * Generated from protobuf field <code>string record_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setRecordId($var)
    {
        GPBUtil::checkString($var, True);
        $this->record_id = $var;

        return $this;
    }

    /**
     * 时间戳
     *
     * Generated from protobuf field <code>int64 timestamp = 5;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * 时间戳
     *
     * Generated from protobuf field <code>int64 timestamp = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * 录制文件上传完成回调
     *
     * Generated from protobuf field <code>.im.v1.VoiceStreamRecordOutputCallback output = 6;</code>
     * @return \Im\V1\VoiceStreamRecordOutputCallback|null
     */
    public function getOutput()
    {
        return $this->output;
    }

    public function hasOutput()
    {
        return isset($this->output);
    }

    public function clearOutput()
    {
        unset($this->output);
    }

    /**
     * 录制文件上传完成回调
     *
     * Generated from protobuf field <code>.im.v1.VoiceStreamRecordOutputCallback output = 6;</code>
     * @param \Im\V1\VoiceStreamRecordOutputCallback $var
     * @return $this
     */
    public function setOutput($var)
    {
        GPBUtil::checkMessage($var, \Im\V1\VoiceStreamRecordOutputCallback::class);
        $this->output = $var;

        return $this;
    }

}

