<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/sync.proto

namespace Im\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>im.v1.VoiceStreamStatusCallback</code>
 */
class VoiceStreamStatusCallback extends \Google\Protobuf\Internal\Message
{
    /**
     * 回调事件类型
     *
     * Generated from protobuf field <code>int64 event = 1;</code>
     */
    protected $event = 0;
    /**
     * 用户ID
     *
     * Generated from protobuf field <code>string user_id = 2;</code>
     */
    protected $user_id = '';
    /**
     * 房间ID
     *
     * Generated from protobuf field <code>string room_id = 3;</code>
     */
    protected $room_id = '';
    /**
     * 房间唯一标识ID
     *
     * Generated from protobuf field <code>string session_id = 4;</code>
     */
    protected $session_id = '';
    /**
     * 时间戳
     *
     * Generated from protobuf field <code>int64 timestamp = 5;</code>
     */
    protected $timestamp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $event
     *           回调事件类型
     *     @type string $user_id
     *           用户ID
     *     @type string $room_id
     *           房间ID
     *     @type string $session_id
     *           房间唯一标识ID
     *     @type int|string $timestamp
     *           时间戳
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Im\V1\Sync::initOnce();
        parent::__construct($data);
    }

    /**
     * 回调事件类型
     *
     * Generated from protobuf field <code>int64 event = 1;</code>
     * @return int|string
     */
    public function getEvent()
    {
        return $this->event;
    }

    /**
     * 回调事件类型
     *
     * Generated from protobuf field <code>int64 event = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEvent($var)
    {
        GPBUtil::checkInt64($var);
        $this->event = $var;

        return $this;
    }

    /**
     * 用户ID
     *
     * Generated from protobuf field <code>string user_id = 2;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * 用户ID
     *
     * Generated from protobuf field <code>string user_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     * 房间ID
     *
     * Generated from protobuf field <code>string room_id = 3;</code>
     * @return string
     */
    public function getRoomId()
    {
        return $this->room_id;
    }

    /**
     * 房间ID
     *
     * Generated from protobuf field <code>string room_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRoomId($var)
    {
        GPBUtil::checkString($var, True);
        $this->room_id = $var;

        return $this;
    }

    /**
     * 房间唯一标识ID
     *
     * Generated from protobuf field <code>string session_id = 4;</code>
     * @return string
     */
    public function getSessionId()
    {
        return $this->session_id;
    }

    /**
     * 房间唯一标识ID
     *
     * Generated from protobuf field <code>string session_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->session_id = $var;

        return $this;
    }

    /**
     * 时间戳
     *
     * Generated from protobuf field <code>int64 timestamp = 5;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * 时间戳
     *
     * Generated from protobuf field <code>int64 timestamp = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

}

