<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/sync.proto

namespace Im\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>im.v1.WebOfficePermission</code>
 */
class WebOfficePermission extends \Google\Protobuf\Internal\Message
{
    /**
     * &#64;gotags: json:"read"
     *
     * Generated from protobuf field <code>int64 read = 1;</code>
     */
    protected $read = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $read
     *           &#64;gotags: json:"read"
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Im\V1\Sync::initOnce();
        parent::__construct($data);
    }

    /**
     * &#64;gotags: json:"read"
     *
     * Generated from protobuf field <code>int64 read = 1;</code>
     * @return int|string
     */
    public function getRead()
    {
        return $this->read;
    }

    /**
     * &#64;gotags: json:"read"
     *
     * Generated from protobuf field <code>int64 read = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRead($var)
    {
        GPBUtil::checkInt64($var);
        $this->read = $var;

        return $this;
    }

}

