<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/schema.proto

namespace Im\V1\Outgoing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 消息数字签名
 *
 * Generated from protobuf message <code>im.v1.Outgoing.Signed</code>
 */
class Signed extends \Google\Protobuf\Internal\Message
{
    /**
     * 数字证书信息
     *
     * Generated from protobuf field <code>bytes certificate = 1;</code>
     */
    protected $certificate = '';
    /**
     * 消息随机安全码
     *
     * Generated from protobuf field <code>string nonce = 2;</code>
     */
    protected $nonce = '';
    /**
     * 消息数字签名
     *
     * Generated from protobuf field <code>string signature = 3;</code>
     */
    protected $signature = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $certificate
     *           数字证书信息
     *     @type string $nonce
     *           消息随机安全码
     *     @type string $signature
     *           消息数字签名
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Im\V1\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * 数字证书信息
     *
     * Generated from protobuf field <code>bytes certificate = 1;</code>
     * @return string
     */
    public function getCertificate()
    {
        return $this->certificate;
    }

    /**
     * 数字证书信息
     *
     * Generated from protobuf field <code>bytes certificate = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCertificate($var)
    {
        GPBUtil::checkString($var, False);
        $this->certificate = $var;

        return $this;
    }

    /**
     * 消息随机安全码
     *
     * Generated from protobuf field <code>string nonce = 2;</code>
     * @return string
     */
    public function getNonce()
    {
        return $this->nonce;
    }

    /**
     * 消息随机安全码
     *
     * Generated from protobuf field <code>string nonce = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNonce($var)
    {
        GPBUtil::checkString($var, True);
        $this->nonce = $var;

        return $this;
    }

    /**
     * 消息数字签名
     *
     * Generated from protobuf field <code>string signature = 3;</code>
     * @return string
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * 消息数字签名
     *
     * Generated from protobuf field <code>string signature = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, True);
        $this->signature = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Signed::class, \Im\V1\Outgoing_Signed::class);

