<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/schema.proto

namespace Im\V1;

if (false) {
    /**
     * This class is deprecated. Use Im\V1\Acked\Error\Category instead.
     * @deprecated
     */
    class Acked_Error_Category {}
}
class_exists(Acked\Error\Category::class);
@trigger_error('Im\V1\Acked_Error_Category is deprecated and will be removed in the next major release. Use Im\V1\Acked\Error\Category instead', E_USER_DEPRECATED);

