<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/schema.proto

namespace Im\V1;

if (false) {
    /**
     * This class is deprecated. Use Im\V1\Data\Category instead.
     * @deprecated
     */
    class Data_Category {}
}
class_exists(Data\Category::class);
@trigger_error('Im\V1\Data_Category is deprecated and will be removed in the next major release. Use Im\V1\Data\Category instead', E_USER_DEPRECATED);

