<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/sync.proto

namespace Im\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>im.v1.Extend</code>
 */
class Extend extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 member_id = 1;</code>
     */
    protected $member_id = 0;
    /**
     * Generated from protobuf field <code>int32 approve_id = 2;</code>
     */
    protected $approve_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $member_id
     *     @type int $approve_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Im\V1\Sync::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 member_id = 1;</code>
     * @return int
     */
    public function getMemberId()
    {
        return $this->member_id;
    }

    /**
     * Generated from protobuf field <code>int32 member_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMemberId($var)
    {
        GPBUtil::checkInt32($var);
        $this->member_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 approve_id = 2;</code>
     * @return int
     */
    public function getApproveId()
    {
        return $this->approve_id;
    }

    /**
     * Generated from protobuf field <code>int32 approve_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setApproveId($var)
    {
        GPBUtil::checkInt32($var);
        $this->approve_id = $var;

        return $this;
    }

}

