<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/schema.proto

namespace Im\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>im.v1.GroupTypCode</code>
 */
class GroupTypCode
{
    /**
     * 普通群
     *
     * Generated from protobuf enum <code>NORMAL = 0;</code>
     */
    const NORMAL = 0;
    /**
     * 部门群
     *
     * Generated from protobuf enum <code>DEPARTMENT = 1;</code>
     */
    const DEPARTMENT = 1;
    /**
     * 公司群
     *
     * Generated from protobuf enum <code>COMPANY = 2;</code>
     */
    const COMPANY = 2;
    /**
     * 内部群
     *
     * Generated from protobuf enum <code>INNER = 3;</code>
     */
    const INNER = 3;

    private static $valueToName = [
        self::NORMAL => 'NORMAL',
        self::DEPARTMENT => 'DEPARTMENT',
        self::COMPANY => 'COMPANY',
        self::INNER => 'INNER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

