<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/schema.proto

namespace Im\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 群组
 *
 * Generated from protobuf message <code>im.v1.Group</code>
 */
class Group extends \Google\Protobuf\Internal\Message
{
    /**
     * &#64;gotags: gorm:"primaryKey" json:"-"
     *
     * Generated from protobuf field <code>int64 lid = 1;</code>
     */
    protected $lid = 0;
    /**
     * &#64;gotags: json:"group"
     *
     * Generated from protobuf field <code>string group = 2;</code>
     */
    protected $group = '';
    /**
     * &#64;gotags: json:"owner"
     *
     * Generated from protobuf field <code>string owner = 3;</code>
     */
    protected $owner = '';
    /**
     * &#64;gotags: json:"team"
     *
     * Generated from protobuf field <code>string team = 4;</code>
     */
    protected $team = '';
    /**
     * &#64;gotags: json:"host"
     *
     * Generated from protobuf field <code>string host = 5;</code>
     */
    protected $host = '';
    /**
     * &#64;gotags: gorm:"serializer:json" json:"path"
     *
     * Generated from protobuf field <code>repeated string path = 6;</code>
     */
    private $path;
    /**
     * &#64;gotags: json:"scene"
     *
     * Generated from protobuf field <code>int32 scene = 7;</code>
     */
    protected $scene = 0;
    /**
     * &#64;gotags: json:"type"
     *
     * Generated from protobuf field <code>int32 type = 8;</code>
     */
    protected $type = 0;
    /**
     * &#64;gotags: json:"creator"
     *
     * Generated from protobuf field <code>string creator = 9;</code>
     */
    protected $creator = '';
    /**
     * &#64;gotags: json:"created"
     *
     * Generated from protobuf field <code>int64 created = 10;</code>
     */
    protected $created = 0;
    /**
     * &#64;gotags: json:"removed"
     *
     * Generated from protobuf field <code>int64 removed = 11;</code>
     */
    protected $removed = 0;
    /**
     * &#64;gotags: json:"updated"
     *
     * Generated from protobuf field <code>int64 updated = 12;</code>
     */
    protected $updated = 0;
    /**
     * &#64;gotags: gorm:"serializer:json" json:"attachment"
     *
     * Generated from protobuf field <code>.im.v1.ClientAttrGroup attachment = 13;</code>
     */
    protected $attachment = null;
    /**
     * &#64;gotags: json:"name"
     *
     * Generated from protobuf field <code>string name = 14;</code>
     */
    protected $name = '';
    /**
     * &#64;gotags: json:"creator_card"
     *
     * Generated from protobuf field <code>string creator_card = 15;</code>
     */
    protected $creator_card = '';
    /**
     * &#64;gotags: gorm:"-" // 本人的成员身份
     *
     * Generated from protobuf field <code>repeated .im.v1.Member members = 16;</code>
     */
    private $members;
    /**
     * &#64;gotags: gorm:"-" json:"total"
     *
     * Generated from protobuf field <code>int64 total = 17;</code>
     */
    protected $total = 0;
    /**
     * &#64;gotags: gorm:"-" json:"sync_disk"
     *
     * Generated from protobuf field <code>bool sync_disk = 18;</code>
     */
    protected $sync_disk = false;
    /**
     * &#64;gotags: gorm:"-" json:"disk_folder"
     *
     * Generated from protobuf field <code>int64 disk_folder = 19;</code>
     */
    protected $disk_folder = 0;
    /**
     * &#64;gotags: gorm:"-"
     *
     * Generated from protobuf field <code>string match_title = 20;</code>
     */
    protected $match_title = '';
    /**
     * &#64;gotags: gorm:"-"
     *
     * Generated from protobuf field <code>int64 match_type = 21;</code>
     */
    protected $match_type = 0;
    /**
     * &#64;gotags: gorm:"-"
     *
     * Generated from protobuf field <code>string card_id = 22;</code>
     */
    protected $card_id = '';
    /**
     * &#64;gotags: json:"birthday_style"
     *
     * Generated from protobuf field <code>string birthday_style = 23;</code>
     */
    protected $birthday_style = '';
    /**
     * &#64;gotags: json:"birthday_notify"
     *
     * Generated from protobuf field <code>bool birthday_notify = 24;</code>
     */
    protected $birthday_notify = false;
    /**
     * &#64;gotags: json:"avatar"
     *
     * Generated from protobuf field <code>string avatar = 25;</code>
     */
    protected $avatar = '';
    /**
     * &#64;gotags: json:"has_invite_member"
     *
     * Generated from protobuf field <code>bool has_invite_member = 26;</code>
     */
    protected $has_invite_member = false;
    /**
     * &#64;gotags: json:"has_look_for_history"
     *
     * Generated from protobuf field <code>bool has_look_for_history = 27;</code>
     */
    protected $has_look_for_history = false;
    /**
     * &#64;gotags: json:"open_cloud_file"
     *
     * Generated from protobuf field <code>bool open_cloud_file = 28;</code>
     */
    protected $open_cloud_file = false;
    /**
     * &#64;gotags: json:"open_picture_file"
     *
     * Generated from protobuf field <code>bool open_picture_file = 29;</code>
     */
    protected $open_picture_file = false;
    /**
     * &#64;gotags: json:"team_name"
     *
     * Generated from protobuf field <code>string team_name = 30;</code>
     */
    protected $team_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $lid
     *           &#64;gotags: gorm:"primaryKey" json:"-"
     *     @type string $group
     *           &#64;gotags: json:"group"
     *     @type string $owner
     *           &#64;gotags: json:"owner"
     *     @type string $team
     *           &#64;gotags: json:"team"
     *     @type string $host
     *           &#64;gotags: json:"host"
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $path
     *           &#64;gotags: gorm:"serializer:json" json:"path"
     *     @type int $scene
     *           &#64;gotags: json:"scene"
     *     @type int $type
     *           &#64;gotags: json:"type"
     *     @type string $creator
     *           &#64;gotags: json:"creator"
     *     @type int|string $created
     *           &#64;gotags: json:"created"
     *     @type int|string $removed
     *           &#64;gotags: json:"removed"
     *     @type int|string $updated
     *           &#64;gotags: json:"updated"
     *     @type \Im\V1\ClientAttrGroup $attachment
     *           &#64;gotags: gorm:"serializer:json" json:"attachment"
     *     @type string $name
     *           &#64;gotags: json:"name"
     *     @type string $creator_card
     *           &#64;gotags: json:"creator_card"
     *     @type \Im\V1\Member[]|\Google\Protobuf\Internal\RepeatedField $members
     *           &#64;gotags: gorm:"-" // 本人的成员身份
     *     @type int|string $total
     *           &#64;gotags: gorm:"-" json:"total"
     *     @type bool $sync_disk
     *           &#64;gotags: gorm:"-" json:"sync_disk"
     *     @type int|string $disk_folder
     *           &#64;gotags: gorm:"-" json:"disk_folder"
     *     @type string $match_title
     *           &#64;gotags: gorm:"-"
     *     @type int|string $match_type
     *           &#64;gotags: gorm:"-"
     *     @type string $card_id
     *           &#64;gotags: gorm:"-"
     *     @type string $birthday_style
     *           &#64;gotags: json:"birthday_style"
     *     @type bool $birthday_notify
     *           &#64;gotags: json:"birthday_notify"
     *     @type string $avatar
     *           &#64;gotags: json:"avatar"
     *     @type bool $has_invite_member
     *           &#64;gotags: json:"has_invite_member"
     *     @type bool $has_look_for_history
     *           &#64;gotags: json:"has_look_for_history"
     *     @type bool $open_cloud_file
     *           &#64;gotags: json:"open_cloud_file"
     *     @type bool $open_picture_file
     *           &#64;gotags: json:"open_picture_file"
     *     @type string $team_name
     *           &#64;gotags: json:"team_name"
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Im\V1\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * &#64;gotags: gorm:"primaryKey" json:"-"
     *
     * Generated from protobuf field <code>int64 lid = 1;</code>
     * @return int|string
     */
    public function getLid()
    {
        return $this->lid;
    }

    /**
     * &#64;gotags: gorm:"primaryKey" json:"-"
     *
     * Generated from protobuf field <code>int64 lid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLid($var)
    {
        GPBUtil::checkInt64($var);
        $this->lid = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"group"
     *
     * Generated from protobuf field <code>string group = 2;</code>
     * @return string
     */
    public function getGroup()
    {
        return $this->group;
    }

    /**
     * &#64;gotags: json:"group"
     *
     * Generated from protobuf field <code>string group = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setGroup($var)
    {
        GPBUtil::checkString($var, True);
        $this->group = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"owner"
     *
     * Generated from protobuf field <code>string owner = 3;</code>
     * @return string
     */
    public function getOwner()
    {
        return $this->owner;
    }

    /**
     * &#64;gotags: json:"owner"
     *
     * Generated from protobuf field <code>string owner = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOwner($var)
    {
        GPBUtil::checkString($var, True);
        $this->owner = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"team"
     *
     * Generated from protobuf field <code>string team = 4;</code>
     * @return string
     */
    public function getTeam()
    {
        return $this->team;
    }

    /**
     * &#64;gotags: json:"team"
     *
     * Generated from protobuf field <code>string team = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTeam($var)
    {
        GPBUtil::checkString($var, True);
        $this->team = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"host"
     *
     * Generated from protobuf field <code>string host = 5;</code>
     * @return string
     */
    public function getHost()
    {
        return $this->host;
    }

    /**
     * &#64;gotags: json:"host"
     *
     * Generated from protobuf field <code>string host = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->host = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"serializer:json" json:"path"
     *
     * Generated from protobuf field <code>repeated string path = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * &#64;gotags: gorm:"serializer:json" json:"path"
     *
     * Generated from protobuf field <code>repeated string path = 6;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPath($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->path = $arr;

        return $this;
    }

    /**
     * &#64;gotags: json:"scene"
     *
     * Generated from protobuf field <code>int32 scene = 7;</code>
     * @return int
     */
    public function getScene()
    {
        return $this->scene;
    }

    /**
     * &#64;gotags: json:"scene"
     *
     * Generated from protobuf field <code>int32 scene = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setScene($var)
    {
        GPBUtil::checkInt32($var);
        $this->scene = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"type"
     *
     * Generated from protobuf field <code>int32 type = 8;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * &#64;gotags: json:"type"
     *
     * Generated from protobuf field <code>int32 type = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->type = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"creator"
     *
     * Generated from protobuf field <code>string creator = 9;</code>
     * @return string
     */
    public function getCreator()
    {
        return $this->creator;
    }

    /**
     * &#64;gotags: json:"creator"
     *
     * Generated from protobuf field <code>string creator = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setCreator($var)
    {
        GPBUtil::checkString($var, True);
        $this->creator = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"created"
     *
     * Generated from protobuf field <code>int64 created = 10;</code>
     * @return int|string
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * &#64;gotags: json:"created"
     *
     * Generated from protobuf field <code>int64 created = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreated($var)
    {
        GPBUtil::checkInt64($var);
        $this->created = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"removed"
     *
     * Generated from protobuf field <code>int64 removed = 11;</code>
     * @return int|string
     */
    public function getRemoved()
    {
        return $this->removed;
    }

    /**
     * &#64;gotags: json:"removed"
     *
     * Generated from protobuf field <code>int64 removed = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRemoved($var)
    {
        GPBUtil::checkInt64($var);
        $this->removed = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"updated"
     *
     * Generated from protobuf field <code>int64 updated = 12;</code>
     * @return int|string
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * &#64;gotags: json:"updated"
     *
     * Generated from protobuf field <code>int64 updated = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpdated($var)
    {
        GPBUtil::checkInt64($var);
        $this->updated = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"serializer:json" json:"attachment"
     *
     * Generated from protobuf field <code>.im.v1.ClientAttrGroup attachment = 13;</code>
     * @return \Im\V1\ClientAttrGroup|null
     */
    public function getAttachment()
    {
        return $this->attachment;
    }

    public function hasAttachment()
    {
        return isset($this->attachment);
    }

    public function clearAttachment()
    {
        unset($this->attachment);
    }

    /**
     * &#64;gotags: gorm:"serializer:json" json:"attachment"
     *
     * Generated from protobuf field <code>.im.v1.ClientAttrGroup attachment = 13;</code>
     * @param \Im\V1\ClientAttrGroup $var
     * @return $this
     */
    public function setAttachment($var)
    {
        GPBUtil::checkMessage($var, \Im\V1\ClientAttrGroup::class);
        $this->attachment = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"name"
     *
     * Generated from protobuf field <code>string name = 14;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * &#64;gotags: json:"name"
     *
     * Generated from protobuf field <code>string name = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"creator_card"
     *
     * Generated from protobuf field <code>string creator_card = 15;</code>
     * @return string
     */
    public function getCreatorCard()
    {
        return $this->creator_card;
    }

    /**
     * &#64;gotags: json:"creator_card"
     *
     * Generated from protobuf field <code>string creator_card = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatorCard($var)
    {
        GPBUtil::checkString($var, True);
        $this->creator_card = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"-" // 本人的成员身份
     *
     * Generated from protobuf field <code>repeated .im.v1.Member members = 16;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMembers()
    {
        return $this->members;
    }

    /**
     * &#64;gotags: gorm:"-" // 本人的成员身份
     *
     * Generated from protobuf field <code>repeated .im.v1.Member members = 16;</code>
     * @param \Im\V1\Member[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMembers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Im\V1\Member::class);
        $this->members = $arr;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"-" json:"total"
     *
     * Generated from protobuf field <code>int64 total = 17;</code>
     * @return int|string
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * &#64;gotags: gorm:"-" json:"total"
     *
     * Generated from protobuf field <code>int64 total = 17;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkInt64($var);
        $this->total = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"-" json:"sync_disk"
     *
     * Generated from protobuf field <code>bool sync_disk = 18;</code>
     * @return bool
     */
    public function getSyncDisk()
    {
        return $this->sync_disk;
    }

    /**
     * &#64;gotags: gorm:"-" json:"sync_disk"
     *
     * Generated from protobuf field <code>bool sync_disk = 18;</code>
     * @param bool $var
     * @return $this
     */
    public function setSyncDisk($var)
    {
        GPBUtil::checkBool($var);
        $this->sync_disk = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"-" json:"disk_folder"
     *
     * Generated from protobuf field <code>int64 disk_folder = 19;</code>
     * @return int|string
     */
    public function getDiskFolder()
    {
        return $this->disk_folder;
    }

    /**
     * &#64;gotags: gorm:"-" json:"disk_folder"
     *
     * Generated from protobuf field <code>int64 disk_folder = 19;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDiskFolder($var)
    {
        GPBUtil::checkInt64($var);
        $this->disk_folder = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"-"
     *
     * Generated from protobuf field <code>string match_title = 20;</code>
     * @return string
     */
    public function getMatchTitle()
    {
        return $this->match_title;
    }

    /**
     * &#64;gotags: gorm:"-"
     *
     * Generated from protobuf field <code>string match_title = 20;</code>
     * @param string $var
     * @return $this
     */
    public function setMatchTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->match_title = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"-"
     *
     * Generated from protobuf field <code>int64 match_type = 21;</code>
     * @return int|string
     */
    public function getMatchType()
    {
        return $this->match_type;
    }

    /**
     * &#64;gotags: gorm:"-"
     *
     * Generated from protobuf field <code>int64 match_type = 21;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMatchType($var)
    {
        GPBUtil::checkInt64($var);
        $this->match_type = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"-"
     *
     * Generated from protobuf field <code>string card_id = 22;</code>
     * @return string
     */
    public function getCardId()
    {
        return $this->card_id;
    }

    /**
     * &#64;gotags: gorm:"-"
     *
     * Generated from protobuf field <code>string card_id = 22;</code>
     * @param string $var
     * @return $this
     */
    public function setCardId($var)
    {
        GPBUtil::checkString($var, True);
        $this->card_id = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"birthday_style"
     *
     * Generated from protobuf field <code>string birthday_style = 23;</code>
     * @return string
     */
    public function getBirthdayStyle()
    {
        return $this->birthday_style;
    }

    /**
     * &#64;gotags: json:"birthday_style"
     *
     * Generated from protobuf field <code>string birthday_style = 23;</code>
     * @param string $var
     * @return $this
     */
    public function setBirthdayStyle($var)
    {
        GPBUtil::checkString($var, True);
        $this->birthday_style = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"birthday_notify"
     *
     * Generated from protobuf field <code>bool birthday_notify = 24;</code>
     * @return bool
     */
    public function getBirthdayNotify()
    {
        return $this->birthday_notify;
    }

    /**
     * &#64;gotags: json:"birthday_notify"
     *
     * Generated from protobuf field <code>bool birthday_notify = 24;</code>
     * @param bool $var
     * @return $this
     */
    public function setBirthdayNotify($var)
    {
        GPBUtil::checkBool($var);
        $this->birthday_notify = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"avatar"
     *
     * Generated from protobuf field <code>string avatar = 25;</code>
     * @return string
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    /**
     * &#64;gotags: json:"avatar"
     *
     * Generated from protobuf field <code>string avatar = 25;</code>
     * @param string $var
     * @return $this
     */
    public function setAvatar($var)
    {
        GPBUtil::checkString($var, True);
        $this->avatar = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"has_invite_member"
     *
     * Generated from protobuf field <code>bool has_invite_member = 26;</code>
     * @return bool
     */
    public function getHasInviteMember()
    {
        return $this->has_invite_member;
    }

    /**
     * &#64;gotags: json:"has_invite_member"
     *
     * Generated from protobuf field <code>bool has_invite_member = 26;</code>
     * @param bool $var
     * @return $this
     */
    public function setHasInviteMember($var)
    {
        GPBUtil::checkBool($var);
        $this->has_invite_member = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"has_look_for_history"
     *
     * Generated from protobuf field <code>bool has_look_for_history = 27;</code>
     * @return bool
     */
    public function getHasLookForHistory()
    {
        return $this->has_look_for_history;
    }

    /**
     * &#64;gotags: json:"has_look_for_history"
     *
     * Generated from protobuf field <code>bool has_look_for_history = 27;</code>
     * @param bool $var
     * @return $this
     */
    public function setHasLookForHistory($var)
    {
        GPBUtil::checkBool($var);
        $this->has_look_for_history = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"open_cloud_file"
     *
     * Generated from protobuf field <code>bool open_cloud_file = 28;</code>
     * @return bool
     */
    public function getOpenCloudFile()
    {
        return $this->open_cloud_file;
    }

    /**
     * &#64;gotags: json:"open_cloud_file"
     *
     * Generated from protobuf field <code>bool open_cloud_file = 28;</code>
     * @param bool $var
     * @return $this
     */
    public function setOpenCloudFile($var)
    {
        GPBUtil::checkBool($var);
        $this->open_cloud_file = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"open_picture_file"
     *
     * Generated from protobuf field <code>bool open_picture_file = 29;</code>
     * @return bool
     */
    public function getOpenPictureFile()
    {
        return $this->open_picture_file;
    }

    /**
     * &#64;gotags: json:"open_picture_file"
     *
     * Generated from protobuf field <code>bool open_picture_file = 29;</code>
     * @param bool $var
     * @return $this
     */
    public function setOpenPictureFile($var)
    {
        GPBUtil::checkBool($var);
        $this->open_picture_file = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"team_name"
     *
     * Generated from protobuf field <code>string team_name = 30;</code>
     * @return string
     */
    public function getTeamName()
    {
        return $this->team_name;
    }

    /**
     * &#64;gotags: json:"team_name"
     *
     * Generated from protobuf field <code>string team_name = 30;</code>
     * @param string $var
     * @return $this
     */
    public function setTeamName($var)
    {
        GPBUtil::checkString($var, True);
        $this->team_name = $var;

        return $this;
    }

}

