<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/schema.proto

namespace Im\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Guide 引导配置
 *
 * Generated from protobuf message <code>im.v1.Guide</code>
 */
class Guide extends \Google\Protobuf\Internal\Message
{
    /**
     * &#64;gotags: gorm:"primaryKey" json:"-"
     *
     * Generated from protobuf field <code>int64 lid = 1;</code>
     */
    protected $lid = 0;
    /**
     * &#64;gotags: json:"typ"
     *
     * Generated from protobuf field <code>string typ = 2;</code>
     */
    protected $typ = '';
    /**
     * &#64;gotags: json:"openid"
     *
     * Generated from protobuf field <code>string openid = 3;</code>
     */
    protected $openid = '';
    /**
     * &#64;gotags: json:"status"
     *
     * Generated from protobuf field <code>bool status = 4;</code>
     */
    protected $status = false;
    /**
     * &#64;gotags: json:"url"
     *
     * Generated from protobuf field <code>string url = 5;</code>
     */
    protected $url = '';
    /**
     * &#64;gotags: json:"created"
     *
     * Generated from protobuf field <code>int64 created = 6;</code>
     */
    protected $created = 0;
    /**
     * &#64;gotags: json:"removed"
     *
     * Generated from protobuf field <code>int64 removed = 7;</code>
     */
    protected $removed = 0;
    /**
     * &#64;gotags: json:"updated"
     *
     * Generated from protobuf field <code>int64 updated = 8;</code>
     */
    protected $updated = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $lid
     *           &#64;gotags: gorm:"primaryKey" json:"-"
     *     @type string $typ
     *           &#64;gotags: json:"typ"
     *     @type string $openid
     *           &#64;gotags: json:"openid"
     *     @type bool $status
     *           &#64;gotags: json:"status"
     *     @type string $url
     *           &#64;gotags: json:"url"
     *     @type int|string $created
     *           &#64;gotags: json:"created"
     *     @type int|string $removed
     *           &#64;gotags: json:"removed"
     *     @type int|string $updated
     *           &#64;gotags: json:"updated"
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Im\V1\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * &#64;gotags: gorm:"primaryKey" json:"-"
     *
     * Generated from protobuf field <code>int64 lid = 1;</code>
     * @return int|string
     */
    public function getLid()
    {
        return $this->lid;
    }

    /**
     * &#64;gotags: gorm:"primaryKey" json:"-"
     *
     * Generated from protobuf field <code>int64 lid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLid($var)
    {
        GPBUtil::checkInt64($var);
        $this->lid = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"typ"
     *
     * Generated from protobuf field <code>string typ = 2;</code>
     * @return string
     */
    public function getTyp()
    {
        return $this->typ;
    }

    /**
     * &#64;gotags: json:"typ"
     *
     * Generated from protobuf field <code>string typ = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTyp($var)
    {
        GPBUtil::checkString($var, True);
        $this->typ = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"openid"
     *
     * Generated from protobuf field <code>string openid = 3;</code>
     * @return string
     */
    public function getOpenid()
    {
        return $this->openid;
    }

    /**
     * &#64;gotags: json:"openid"
     *
     * Generated from protobuf field <code>string openid = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOpenid($var)
    {
        GPBUtil::checkString($var, True);
        $this->openid = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"status"
     *
     * Generated from protobuf field <code>bool status = 4;</code>
     * @return bool
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * &#64;gotags: json:"status"
     *
     * Generated from protobuf field <code>bool status = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkBool($var);
        $this->status = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"url"
     *
     * Generated from protobuf field <code>string url = 5;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * &#64;gotags: json:"url"
     *
     * Generated from protobuf field <code>string url = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"created"
     *
     * Generated from protobuf field <code>int64 created = 6;</code>
     * @return int|string
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * &#64;gotags: json:"created"
     *
     * Generated from protobuf field <code>int64 created = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreated($var)
    {
        GPBUtil::checkInt64($var);
        $this->created = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"removed"
     *
     * Generated from protobuf field <code>int64 removed = 7;</code>
     * @return int|string
     */
    public function getRemoved()
    {
        return $this->removed;
    }

    /**
     * &#64;gotags: json:"removed"
     *
     * Generated from protobuf field <code>int64 removed = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRemoved($var)
    {
        GPBUtil::checkInt64($var);
        $this->removed = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"updated"
     *
     * Generated from protobuf field <code>int64 updated = 8;</code>
     * @return int|string
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * &#64;gotags: json:"updated"
     *
     * Generated from protobuf field <code>int64 updated = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpdated($var)
    {
        GPBUtil::checkInt64($var);
        $this->updated = $var;

        return $this;
    }

}

