<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/sync.proto

namespace Im\V1;

/**
 * GuideSrv 引导服务
 *
 * Protobuf type <code>im.v1.GuideSrv</code>
 */
interface GuideSrvInterface
{
    /**
     * CreateGuid 获取引导状态
     *
     * Method <code>getGuide</code>
     *
     * @param \Im\V1\GuidTyp $request
     * @return \Im\V1\Guide
     */
    public function getGuide(\Im\V1\GuidTyp $request);

    /**
     * FinishGuid 完成引导
     *
     * Method <code>finishGuide</code>
     *
     * @param \Im\V1\GuidTyp $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function finishGuide(\Im\V1\GuidTyp $request);

}

