<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/schema.proto

namespace Im\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 接入定义
 *
 * Generated from protobuf message <code>im.v1.Incoming</code>
 */
class Incoming extends \Google\Protobuf\Internal\Message
{
    /**
     * 系统通知推送模式
     *
     * Generated from protobuf field <code>.im.v1.Incoming.OSPushMode push = 1;</code>
     */
    protected $push = 0;
    protected $received;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $push
     *           系统通知推送模式
     *     @type \Im\V1\Incoming\Shared $shared
     *           共享消息
     *     @type \Im\V1\Incoming\PBPrivate $private
     *           专有消息
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Im\V1\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * 系统通知推送模式
     *
     * Generated from protobuf field <code>.im.v1.Incoming.OSPushMode push = 1;</code>
     * @return int
     */
    public function getPush()
    {
        return $this->push;
    }

    /**
     * 系统通知推送模式
     *
     * Generated from protobuf field <code>.im.v1.Incoming.OSPushMode push = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPush($var)
    {
        GPBUtil::checkEnum($var, \Im\V1\Incoming\OSPushMode::class);
        $this->push = $var;

        return $this;
    }

    /**
     * 共享消息
     *
     * Generated from protobuf field <code>.im.v1.Incoming.Shared shared = 2;</code>
     * @return \Im\V1\Incoming\Shared|null
     */
    public function getShared()
    {
        return $this->readOneof(2);
    }

    public function hasShared()
    {
        return $this->hasOneof(2);
    }

    /**
     * 共享消息
     *
     * Generated from protobuf field <code>.im.v1.Incoming.Shared shared = 2;</code>
     * @param \Im\V1\Incoming\Shared $var
     * @return $this
     */
    public function setShared($var)
    {
        GPBUtil::checkMessage($var, \Im\V1\Incoming\Shared::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * 专有消息
     *
     * Generated from protobuf field <code>.im.v1.Incoming.Private private = 3;</code>
     * @return \Im\V1\Incoming\PBPrivate|null
     */
    public function getPrivate()
    {
        return $this->readOneof(3);
    }

    public function hasPrivate()
    {
        return $this->hasOneof(3);
    }

    /**
     * 专有消息
     *
     * Generated from protobuf field <code>.im.v1.Incoming.Private private = 3;</code>
     * @param \Im\V1\Incoming\PBPrivate $var
     * @return $this
     */
    public function setPrivate($var)
    {
        GPBUtil::checkMessage($var, \Im\V1\Incoming\PBPrivate::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getReceived()
    {
        return $this->whichOneof("received");
    }

}

