<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/schema.proto

namespace Im\V1;

if (false) {
    /**
     * This class is deprecated. Use Im\V1\Incoming\Shared instead.
     * @deprecated
     */
    class Incoming_Shared {}
}
class_exists(Incoming\Shared::class);
@trigger_error('Im\V1\Incoming_Shared is deprecated and will be removed in the next major release. Use Im\V1\Incoming\Shared instead', E_USER_DEPRECATED);

