<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/schema.proto

namespace Im\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 接入的端口信息
 *
 * Generated from protobuf message <code>im.v1.IO</code>
 */
class IO extends \Google\Protobuf\Internal\Message
{
    /**
     * 设备，从设备注册表获得，而非从客户端上传
     *
     * Generated from protobuf field <code>.im.v1.IO.Device device = 1;</code>
     */
    protected $device = null;
    /**
     * 接入的 WebSocket 端口
     *
     * Generated from protobuf field <code>uint64 socket = 2;</code>
     */
    protected $socket = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Im\V1\IO\Device $device
     *           设备，从设备注册表获得，而非从客户端上传
     *     @type int|string $socket
     *           接入的 WebSocket 端口
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Im\V1\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * 设备，从设备注册表获得，而非从客户端上传
     *
     * Generated from protobuf field <code>.im.v1.IO.Device device = 1;</code>
     * @return \Im\V1\IO\Device|null
     */
    public function getDevice()
    {
        return $this->device;
    }

    public function hasDevice()
    {
        return isset($this->device);
    }

    public function clearDevice()
    {
        unset($this->device);
    }

    /**
     * 设备，从设备注册表获得，而非从客户端上传
     *
     * Generated from protobuf field <code>.im.v1.IO.Device device = 1;</code>
     * @param \Im\V1\IO\Device $var
     * @return $this
     */
    public function setDevice($var)
    {
        GPBUtil::checkMessage($var, \Im\V1\IO\Device::class);
        $this->device = $var;

        return $this;
    }

    /**
     * 接入的 WebSocket 端口
     *
     * Generated from protobuf field <code>uint64 socket = 2;</code>
     * @return int|string
     */
    public function getSocket()
    {
        return $this->socket;
    }

    /**
     * 接入的 WebSocket 端口
     *
     * Generated from protobuf field <code>uint64 socket = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSocket($var)
    {
        GPBUtil::checkUint64($var);
        $this->socket = $var;

        return $this;
    }

}

