<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/schema.proto

namespace Im\V1;

if (false) {
    /**
     * This class is deprecated. Use Im\V1\IO\Device\Type instead.
     * @deprecated
     */
    class IO_Device_Type {}
}
class_exists(IO\Device\Type::class);
@trigger_error('Im\V1\IO_Device_Type is deprecated and will be removed in the next major release. Use Im\V1\IO\Device\Type instead', E_USER_DEPRECATED);

