<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/sync.proto

namespace Im\V1;

/**
 * 会议相关服务
 *
 * Protobuf type <code>im.v1.MeetingSrv</code>
 */
interface MeetingSrvInterface
{
    /**
     * CreateMeeting 创建会议
     *
     * Method <code>createMeeting</code>
     *
     * @param \Im\V1\Meeting $request
     * @return \Im\V1\ID
     */
    public function createMeeting(\Im\V1\Meeting $request);

    /**
     * GetMeeting 查询会议
     *
     * Method <code>getMeeting</code>
     *
     * @param \Im\V1\ID $request
     * @return \Im\V1\Meeting
     */
    public function getMeeting(\Im\V1\ID $request);

    /**
     * RCVoiceStream 融云会议录制结果查询
     *
     * Method <code>rCVoiceStream</code>
     *
     * @param \Im\V1\QueryVoiceStreamRecord $request
     * @return \Im\V1\MeetingRecord
     */
    public function rCVoiceStream(\Im\V1\QueryVoiceStreamRecord $request);

    /**
     * RCVoiceStreamRecord 融云会议录制
     *
     * Method <code>rCVoiceStreamRecord</code>
     *
     * @param \Im\V1\VoiceStreamRecordReq $request
     * @return \Im\V1\VoiceStreamRecordResp
     */
    public function rCVoiceStreamRecord(\Im\V1\VoiceStreamRecordReq $request);

    /**
     * RCVoiceStreamRecordCallback 融云录音回调
     *
     * Method <code>rCVoiceStreamRecordCallback</code>
     *
     * @param \Im\V1\VoiceStreamRecordCallback $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function rCVoiceStreamRecordCallback(\Im\V1\VoiceStreamRecordCallback $request);

    /**
     * RCVoiceStreamStatusCallback 融云会议状态回调
     *
     * Method <code>rCVoiceStreamStatusCallback</code>
     *
     * @param \Im\V1\VoiceStreamStatusCallback $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function rCVoiceStreamStatusCallback(\Im\V1\VoiceStreamStatusCallback $request);

}

