<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/sync.proto

namespace Im\V1;

/**
 * 会议邀请服务
 *
 * Protobuf type <code>im.v1.MeetingInviteSrv</code>
 */
interface MeetingInviteSrvInterface
{
    /**
     * CreateMeetings 批量创建会议邀请
     *
     * Method <code>createMeetingInvites</code>
     *
     * @param \Im\V1\MeetingInviteBatch $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function createMeetingInvites(\Im\V1\MeetingInviteBatch $request);

    /**
     * MeetingInviteSearch 查询会议邀请列表
     *
     * Method <code>meetingInviteSearch</code>
     *
     * @param \Im\V1\ID $request
     * @return \Im\V1\MeetingInviteBatch
     */
    public function meetingInviteSearch(\Im\V1\ID $request);

    /**
     * DeleteMeetingInvite 删除邀请
     *
     * Method <code>deleteMeetingInvite</code>
     *
     * @param \Im\V1\ID $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function deleteMeetingInvite(\Im\V1\ID $request);

}

