<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/sync.proto

namespace Im\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>im.v1.MeetingInviteBatch</code>
 */
class MeetingInviteBatch extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .im.v1.MeetingInvite invites = 1;</code>
     */
    private $invites;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Im\V1\MeetingInvite[]|\Google\Protobuf\Internal\RepeatedField $invites
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Im\V1\Sync::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .im.v1.MeetingInvite invites = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInvites()
    {
        return $this->invites;
    }

    /**
     * Generated from protobuf field <code>repeated .im.v1.MeetingInvite invites = 1;</code>
     * @param \Im\V1\MeetingInvite[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInvites($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Im\V1\MeetingInvite::class);
        $this->invites = $arr;

        return $this;
    }

}

