<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/schema.proto

namespace Im\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 群成员
 *
 * Generated from protobuf message <code>im.v1.Member</code>
 */
class Member extends \Google\Protobuf\Internal\Message
{
    /**
     * &#64;gotags: gorm:"primaryKey" json:"-"
     *
     * Generated from protobuf field <code>int64 lid = 1;</code>
     */
    protected $lid = 0;
    /**
     * &#64;gotags: json:"group"
     *
     * Generated from protobuf field <code>string group = 2;</code>
     */
    protected $group = '';
    /**
     * &#64;gotags: json:"openid"
     *
     * Generated from protobuf field <code>string openid = 4;</code>
     */
    protected $openid = '';
    /**
     * &#64;gotags: gorm:"serializer:json" json:"roles"
     *
     * Generated from protobuf field <code>repeated string roles = 5;</code>
     */
    private $roles;
    /**
     * &#64;gotags: gorm:"serializer:json" json:"badges"
     *
     * Generated from protobuf field <code>repeated string badges = 6;</code>
     */
    private $badges;
    /**
     * &#64;gotags: json:"banned"
     *
     * Generated from protobuf field <code>int64 banned = 7;</code>
     */
    protected $banned = 0;
    /**
     * &#64;gotags: json:"disabled"
     *
     * Generated from protobuf field <code>int64 disabled = 8;</code>
     */
    protected $disabled = 0;
    /**
     * &#64;gotags: json:"joined"
     *
     * Generated from protobuf field <code>int64 joined = 9;</code>
     */
    protected $joined = 0;
    /**
     * &#64;gotags: json:"removed"
     *
     * Generated from protobuf field <code>int64 removed = 10;</code>
     */
    protected $removed = 0;
    /**
     * &#64;gotags: json:"latest"
     *
     * Generated from protobuf field <code>int64 latest = 11;</code>
     */
    protected $latest = 0;
    /**
     * &#64;gotags: gorm:"serializer:json" json:"attachments"
     *
     * Generated from protobuf field <code>.google.protobuf.Struct attachments = 12;</code>
     */
    protected $attachments = null;
    /**
     * &#64;gotags: json:"addr"
     *
     * Generated from protobuf field <code>bool addr = 13;</code>
     */
    protected $addr = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $lid
     *           &#64;gotags: gorm:"primaryKey" json:"-"
     *     @type string $group
     *           &#64;gotags: json:"group"
     *     @type string $openid
     *           &#64;gotags: json:"openid"
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $roles
     *           &#64;gotags: gorm:"serializer:json" json:"roles"
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $badges
     *           &#64;gotags: gorm:"serializer:json" json:"badges"
     *     @type int|string $banned
     *           &#64;gotags: json:"banned"
     *     @type int|string $disabled
     *           &#64;gotags: json:"disabled"
     *     @type int|string $joined
     *           &#64;gotags: json:"joined"
     *     @type int|string $removed
     *           &#64;gotags: json:"removed"
     *     @type int|string $latest
     *           &#64;gotags: json:"latest"
     *     @type \Google\Protobuf\Struct $attachments
     *           &#64;gotags: gorm:"serializer:json" json:"attachments"
     *     @type bool $addr
     *           &#64;gotags: json:"addr"
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Im\V1\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * &#64;gotags: gorm:"primaryKey" json:"-"
     *
     * Generated from protobuf field <code>int64 lid = 1;</code>
     * @return int|string
     */
    public function getLid()
    {
        return $this->lid;
    }

    /**
     * &#64;gotags: gorm:"primaryKey" json:"-"
     *
     * Generated from protobuf field <code>int64 lid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLid($var)
    {
        GPBUtil::checkInt64($var);
        $this->lid = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"group"
     *
     * Generated from protobuf field <code>string group = 2;</code>
     * @return string
     */
    public function getGroup()
    {
        return $this->group;
    }

    /**
     * &#64;gotags: json:"group"
     *
     * Generated from protobuf field <code>string group = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setGroup($var)
    {
        GPBUtil::checkString($var, True);
        $this->group = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"openid"
     *
     * Generated from protobuf field <code>string openid = 4;</code>
     * @return string
     */
    public function getOpenid()
    {
        return $this->openid;
    }

    /**
     * &#64;gotags: json:"openid"
     *
     * Generated from protobuf field <code>string openid = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setOpenid($var)
    {
        GPBUtil::checkString($var, True);
        $this->openid = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"serializer:json" json:"roles"
     *
     * Generated from protobuf field <code>repeated string roles = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRoles()
    {
        return $this->roles;
    }

    /**
     * &#64;gotags: gorm:"serializer:json" json:"roles"
     *
     * Generated from protobuf field <code>repeated string roles = 5;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRoles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->roles = $arr;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"serializer:json" json:"badges"
     *
     * Generated from protobuf field <code>repeated string badges = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBadges()
    {
        return $this->badges;
    }

    /**
     * &#64;gotags: gorm:"serializer:json" json:"badges"
     *
     * Generated from protobuf field <code>repeated string badges = 6;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBadges($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->badges = $arr;

        return $this;
    }

    /**
     * &#64;gotags: json:"banned"
     *
     * Generated from protobuf field <code>int64 banned = 7;</code>
     * @return int|string
     */
    public function getBanned()
    {
        return $this->banned;
    }

    /**
     * &#64;gotags: json:"banned"
     *
     * Generated from protobuf field <code>int64 banned = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBanned($var)
    {
        GPBUtil::checkInt64($var);
        $this->banned = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"disabled"
     *
     * Generated from protobuf field <code>int64 disabled = 8;</code>
     * @return int|string
     */
    public function getDisabled()
    {
        return $this->disabled;
    }

    /**
     * &#64;gotags: json:"disabled"
     *
     * Generated from protobuf field <code>int64 disabled = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDisabled($var)
    {
        GPBUtil::checkInt64($var);
        $this->disabled = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"joined"
     *
     * Generated from protobuf field <code>int64 joined = 9;</code>
     * @return int|string
     */
    public function getJoined()
    {
        return $this->joined;
    }

    /**
     * &#64;gotags: json:"joined"
     *
     * Generated from protobuf field <code>int64 joined = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setJoined($var)
    {
        GPBUtil::checkInt64($var);
        $this->joined = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"removed"
     *
     * Generated from protobuf field <code>int64 removed = 10;</code>
     * @return int|string
     */
    public function getRemoved()
    {
        return $this->removed;
    }

    /**
     * &#64;gotags: json:"removed"
     *
     * Generated from protobuf field <code>int64 removed = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRemoved($var)
    {
        GPBUtil::checkInt64($var);
        $this->removed = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"latest"
     *
     * Generated from protobuf field <code>int64 latest = 11;</code>
     * @return int|string
     */
    public function getLatest()
    {
        return $this->latest;
    }

    /**
     * &#64;gotags: json:"latest"
     *
     * Generated from protobuf field <code>int64 latest = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLatest($var)
    {
        GPBUtil::checkInt64($var);
        $this->latest = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"serializer:json" json:"attachments"
     *
     * Generated from protobuf field <code>.google.protobuf.Struct attachments = 12;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getAttachments()
    {
        return $this->attachments;
    }

    public function hasAttachments()
    {
        return isset($this->attachments);
    }

    public function clearAttachments()
    {
        unset($this->attachments);
    }

    /**
     * &#64;gotags: gorm:"serializer:json" json:"attachments"
     *
     * Generated from protobuf field <code>.google.protobuf.Struct attachments = 12;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setAttachments($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->attachments = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"addr"
     *
     * Generated from protobuf field <code>bool addr = 13;</code>
     * @return bool
     */
    public function getAddr()
    {
        return $this->addr;
    }

    /**
     * &#64;gotags: json:"addr"
     *
     * Generated from protobuf field <code>bool addr = 13;</code>
     * @param bool $var
     * @return $this
     */
    public function setAddr($var)
    {
        GPBUtil::checkBool($var);
        $this->addr = $var;

        return $this;
    }

}

