<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/sync.proto

namespace Im\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>im.v1.MemberCreat</code>
 */
class MemberCreat extends \Google\Protobuf\Internal\Message
{
    /**
     * 在融云注册的ID，再次加群不用传
     *
     * Generated from protobuf field <code>string rid = 1;</code>
     */
    protected $rid = '';
    /**
     * Generated from protobuf field <code>.im.v1.Member member = 2;</code>
     */
    protected $member = null;
    /**
     * 操作人员身份卡ID
     *
     * Generated from protobuf field <code>string op_card_id = 3;</code>
     */
    protected $op_card_id = '';
    /**
     * 是否服务端调用
     *
     * Generated from protobuf field <code>bool from_server = 4;</code>
     */
    protected $from_server = false;
    /**
     * 是否扫码调用
     *
     * Generated from protobuf field <code>bool from_qrcode = 5;</code>
     */
    protected $from_qrcode = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $rid
     *           在融云注册的ID，再次加群不用传
     *     @type \Im\V1\Member $member
     *     @type string $op_card_id
     *           操作人员身份卡ID
     *     @type bool $from_server
     *           是否服务端调用
     *     @type bool $from_qrcode
     *           是否扫码调用
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Im\V1\Sync::initOnce();
        parent::__construct($data);
    }

    /**
     * 在融云注册的ID，再次加群不用传
     *
     * Generated from protobuf field <code>string rid = 1;</code>
     * @return string
     */
    public function getRid()
    {
        return $this->rid;
    }

    /**
     * 在融云注册的ID，再次加群不用传
     *
     * Generated from protobuf field <code>string rid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRid($var)
    {
        GPBUtil::checkString($var, True);
        $this->rid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.im.v1.Member member = 2;</code>
     * @return \Im\V1\Member|null
     */
    public function getMember()
    {
        return $this->member;
    }

    public function hasMember()
    {
        return isset($this->member);
    }

    public function clearMember()
    {
        unset($this->member);
    }

    /**
     * Generated from protobuf field <code>.im.v1.Member member = 2;</code>
     * @param \Im\V1\Member $var
     * @return $this
     */
    public function setMember($var)
    {
        GPBUtil::checkMessage($var, \Im\V1\Member::class);
        $this->member = $var;

        return $this;
    }

    /**
     * 操作人员身份卡ID
     *
     * Generated from protobuf field <code>string op_card_id = 3;</code>
     * @return string
     */
    public function getOpCardId()
    {
        return $this->op_card_id;
    }

    /**
     * 操作人员身份卡ID
     *
     * Generated from protobuf field <code>string op_card_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOpCardId($var)
    {
        GPBUtil::checkString($var, True);
        $this->op_card_id = $var;

        return $this;
    }

    /**
     * 是否服务端调用
     *
     * Generated from protobuf field <code>bool from_server = 4;</code>
     * @return bool
     */
    public function getFromServer()
    {
        return $this->from_server;
    }

    /**
     * 是否服务端调用
     *
     * Generated from protobuf field <code>bool from_server = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setFromServer($var)
    {
        GPBUtil::checkBool($var);
        $this->from_server = $var;

        return $this;
    }

    /**
     * 是否扫码调用
     *
     * Generated from protobuf field <code>bool from_qrcode = 5;</code>
     * @return bool
     */
    public function getFromQrcode()
    {
        return $this->from_qrcode;
    }

    /**
     * 是否扫码调用
     *
     * Generated from protobuf field <code>bool from_qrcode = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setFromQrcode($var)
    {
        GPBUtil::checkBool($var);
        $this->from_qrcode = $var;

        return $this;
    }

}

