<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/schema.proto

namespace Im\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 消息元信息，用于标识消息
 *
 * Generated from protobuf message <code>im.v1.Meta</code>
 */
class Meta extends \Google\Protobuf\Internal\Message
{
    /**
     * 发件端本地消息行号，仅发件端有用
     *
     * Generated from protobuf field <code>uint64 rowid = 1;</code>
     */
    protected $rowid = 0;
    /**
     * 消息唯一标识符
     *
     * Generated from protobuf field <code>uint64 msg_id = 2;</code>
     */
    protected $msg_id = 0;
    /**
     * 严格顺序消息序号
     *
     * Generated from protobuf field <code>uint64 seq_id = 3;</code>
     */
    protected $seq_id = 0;
    /**
     * 消息发件时间戳
     *
     * Generated from protobuf field <code>uint64 timestamp = 4;</code>
     */
    protected $timestamp = 0;
    /**
     * （持久化时的）存储顺序号，（同步队列）消息顺序号
     *
     * Generated from protobuf field <code>uint64 order = 5;</code>
     */
    protected $order = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $rowid
     *           发件端本地消息行号，仅发件端有用
     *     @type int|string $msg_id
     *           消息唯一标识符
     *     @type int|string $seq_id
     *           严格顺序消息序号
     *     @type int|string $timestamp
     *           消息发件时间戳
     *     @type int|string $order
     *           （持久化时的）存储顺序号，（同步队列）消息顺序号
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Im\V1\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * 发件端本地消息行号，仅发件端有用
     *
     * Generated from protobuf field <code>uint64 rowid = 1;</code>
     * @return int|string
     */
    public function getRowid()
    {
        return $this->rowid;
    }

    /**
     * 发件端本地消息行号，仅发件端有用
     *
     * Generated from protobuf field <code>uint64 rowid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRowid($var)
    {
        GPBUtil::checkUint64($var);
        $this->rowid = $var;

        return $this;
    }

    /**
     * 消息唯一标识符
     *
     * Generated from protobuf field <code>uint64 msg_id = 2;</code>
     * @return int|string
     */
    public function getMsgId()
    {
        return $this->msg_id;
    }

    /**
     * 消息唯一标识符
     *
     * Generated from protobuf field <code>uint64 msg_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMsgId($var)
    {
        GPBUtil::checkUint64($var);
        $this->msg_id = $var;

        return $this;
    }

    /**
     * 严格顺序消息序号
     *
     * Generated from protobuf field <code>uint64 seq_id = 3;</code>
     * @return int|string
     */
    public function getSeqId()
    {
        return $this->seq_id;
    }

    /**
     * 严格顺序消息序号
     *
     * Generated from protobuf field <code>uint64 seq_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSeqId($var)
    {
        GPBUtil::checkUint64($var);
        $this->seq_id = $var;

        return $this;
    }

    /**
     * 消息发件时间戳
     *
     * Generated from protobuf field <code>uint64 timestamp = 4;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * 消息发件时间戳
     *
     * Generated from protobuf field <code>uint64 timestamp = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * （持久化时的）存储顺序号，（同步队列）消息顺序号
     *
     * Generated from protobuf field <code>uint64 order = 5;</code>
     * @return int|string
     */
    public function getOrder()
    {
        return $this->order;
    }

    /**
     * （持久化时的）存储顺序号，（同步队列）消息顺序号
     *
     * Generated from protobuf field <code>uint64 order = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrder($var)
    {
        GPBUtil::checkUint64($var);
        $this->order = $var;

        return $this;
    }

}

