<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/sync.proto

namespace Im\V1;

/**
 * 通知&消息相关服务
 *
 * Protobuf type <code>im.v1.NotifySrv</code>
 */
interface NotifySrvInterface
{
    /**
     * Send 发送消息
     *
     * Method <code>send</code>
     *
     * @param \Im\V1\ThirdMessage $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function send(\Im\V1\ThirdMessage $request);

    /**
     * UpdateNotify 编辑通知配置，不存在就创建
     *
     * Method <code>updateNotify</code>
     *
     * @param \Im\V1\Notify $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function updateNotify(\Im\V1\Notify $request);

    /**
     * ListNotify 分页查询通知
     *
     * Method <code>listNotify</code>
     *
     * @param \Im\V1\Pagination $request
     * @return \Im\V1\RespArr
     */
    public function listNotify(\Im\V1\Pagination $request);

}

