<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/sync.proto

namespace Im\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>im.v1.NotifyScene</code>
 */
class NotifyScene
{
    /**
     * 创建
     *
     * Generated from protobuf enum <code>CREATE = 0;</code>
     */
    const CREATE = 0;
    /**
     * 更新
     *
     * Generated from protobuf enum <code>UPDATE = 1;</code>
     */
    const UPDATE = 1;
    /**
     * 删除
     *
     * Generated from protobuf enum <code>DELETE = 2;</code>
     */
    const DELETE = 2;
    /**
     * 批量删除
     *
     * Generated from protobuf enum <code>BATCH_DEL = 3;</code>
     */
    const BATCH_DEL = 3;
    /**
     * 批量添加
     *
     * Generated from protobuf enum <code>BATCH_ADD = 4;</code>
     */
    const BATCH_ADD = 4;
    /**
     * 群转让
     *
     * Generated from protobuf enum <code>OWNER_TRANSFER = 5;</code>
     */
    const OWNER_TRANSFER = 5;
    /**
     * 入群申请
     *
     * Generated from protobuf enum <code>GROUP_APPLY = 6;</code>
     */
    const GROUP_APPLY = 6;
    /**
     * 自己退群
     *
     * Generated from protobuf enum <code>GROUP_SELF_DEL = 7;</code>
     */
    const GROUP_SELF_DEL = 7;
    /**
     * 用户注销下线
     *
     * Generated from protobuf enum <code>OFF_LINE = 8;</code>
     */
    const OFF_LINE = 8;
    /**
     * 身份卡移除
     *
     * Generated from protobuf enum <code>CARD_ID_REMOVE = 9;</code>
     */
    const CARD_ID_REMOVE = 9;
    /**
     * 身份卡增加
     *
     * Generated from protobuf enum <code>CARD_ID_ADD = 10;</code>
     */
    const CARD_ID_ADD = 10;
    /**
     * 修改密码下线
     *
     * Generated from protobuf enum <code>PASSWORD_UPDATE = 11;</code>
     */
    const PASSWORD_UPDATE = 11;
    /**
     * 抢登下线
     *
     * Generated from protobuf enum <code>ONLINE_OTHER_DEVICE = 12;</code>
     */
    const ONLINE_OTHER_DEVICE = 12;
    /**
     * 组织踢出
     *
     * Generated from protobuf enum <code>TEAM_DEL = 13;</code>
     */
    const TEAM_DEL = 13;
    /**
     * 面对面建群
     *
     * Generated from protobuf enum <code>FACE2FACE = 14;</code>
     */
    const FACE2FACE = 14;
    /**
     * 账号违规封禁，下线
     *
     * Generated from protobuf enum <code>BAN_OFF_LINE = 15;</code>
     */
    const BAN_OFF_LINE = 15;
    /**
     * 提醒更新
     *
     * Generated from protobuf enum <code>UPDATE_NOTICE = 17;</code>
     */
    const UPDATE_NOTICE = 17;

    private static $valueToName = [
        self::CREATE => 'CREATE',
        self::UPDATE => 'UPDATE',
        self::DELETE => 'DELETE',
        self::BATCH_DEL => 'BATCH_DEL',
        self::BATCH_ADD => 'BATCH_ADD',
        self::OWNER_TRANSFER => 'OWNER_TRANSFER',
        self::GROUP_APPLY => 'GROUP_APPLY',
        self::GROUP_SELF_DEL => 'GROUP_SELF_DEL',
        self::OFF_LINE => 'OFF_LINE',
        self::CARD_ID_REMOVE => 'CARD_ID_REMOVE',
        self::CARD_ID_ADD => 'CARD_ID_ADD',
        self::PASSWORD_UPDATE => 'PASSWORD_UPDATE',
        self::ONLINE_OTHER_DEVICE => 'ONLINE_OTHER_DEVICE',
        self::TEAM_DEL => 'TEAM_DEL',
        self::FACE2FACE => 'FACE2FACE',
        self::BAN_OFF_LINE => 'BAN_OFF_LINE',
        self::UPDATE_NOTICE => 'UPDATE_NOTICE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

