<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/sync.proto

namespace Im\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>im.v1.NotifyTyp</code>
 */
class NotifyTyp
{
    /**
     * 知行提醒
     *
     * Generated from protobuf enum <code>APP_KNOW = 0;</code>
     */
    const APP_KNOW = 0;
    /**
     * 广场提醒
     *
     * Generated from protobuf enum <code>APP_SQUARE = 1;</code>
     */
    const APP_SQUARE = 1;
    /**
     * 全部提醒
     *
     * Generated from protobuf enum <code>APP_NOTIFY = 2;</code>
     */
    const APP_NOTIFY = 2;
    /**
     * 云盘提醒
     *
     * Generated from protobuf enum <code>APP_CLOUD_DISK = 3;</code>
     */
    const APP_CLOUD_DISK = 3;

    private static $valueToName = [
        self::APP_KNOW => 'APP_KNOW',
        self::APP_SQUARE => 'APP_SQUARE',
        self::APP_NOTIFY => 'APP_NOTIFY',
        self::APP_CLOUD_DISK => 'APP_CLOUD_DISK',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

