<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/schema.proto

namespace Im\V1;

if (false) {
    /**
     * This class is deprecated. Use Im\V1\Outgoing\Signed instead.
     * @deprecated
     */
    class Outgoing_Signed {}
}
class_exists(Outgoing\Signed::class);
@trigger_error('Im\V1\Outgoing_Signed is deprecated and will be removed in the next major release. Use Im\V1\Outgoing\Signed instead', E_USER_DEPRECATED);

