<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/sync.proto

namespace Im\V1;

/**
 * IM关系服务
 *
 * Protobuf type <code>im.v1.PairSrv</code>
 */
interface PairSrvInterface
{
    /**
     * CreatePair 创建关系
     *
     * Method <code>createPair</code>
     *
     * @param \Im\V1\Pair $request
     * @return \Im\V1\Pair
     */
    public function createPair(\Im\V1\Pair $request);

    /**
     * GetPair 查询关系
     *
     * Method <code>getPair</code>
     *
     * @param \Im\V1\PairID $request
     * @return \Im\V1\Pair
     */
    public function getPair(\Im\V1\PairID $request);

    /**
     * UpdatePair 编辑关系
     *
     * Method <code>updatePair</code>
     *
     * @param \Im\V1\Pair $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function updatePair(\Im\V1\Pair $request);

    /**
     * DeletePair 删除关系
     *
     * Method <code>deletePair</code>
     *
     * @param \Im\V1\PairID $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function deletePair(\Im\V1\PairID $request);

    /**
     * ListPair 分页查询关系
     *
     * Method <code>listPair</code>
     *
     * @param \Im\V1\Pagination $request
     * @return \Im\V1\RespArr
     */
    public function listPair(\Im\V1\Pagination $request);

    /**
     * UpdatePairActive 更新活跃时间
     *
     * Method <code>updatePairActive</code>
     *
     * @param \Im\V1\PairID $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function updatePairActive(\Im\V1\PairID $request);

    /**
     * PairCreatedCheck 已创建关系检查
     *
     * Method <code>pairCreatedCheck</code>
     *
     * @param \Im\V1\PairRelaStatusQuery $request
     * @return \Im\V1\PairRelaStatus
     */
    public function pairCreatedCheck(\Im\V1\PairRelaStatusQuery $request);

}

