<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/sync.proto

namespace Im\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>im.v1.PairRelaStatus</code>
 */
class PairRelaStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, .im.v1.PairIDs> rela = 1;</code>
     */
    private $rela;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $rela
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Im\V1\Sync::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, .im.v1.PairIDs> rela = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getRela()
    {
        return $this->rela;
    }

    /**
     * Generated from protobuf field <code>map<string, .im.v1.PairIDs> rela = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setRela($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Im\V1\PairIDs::class);
        $this->rela = $arr;

        return $this;
    }

}

