<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/schema.proto

namespace Im\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 关系
 *
 * Generated from protobuf message <code>im.v1.Pair</code>
 */
class Pair extends \Google\Protobuf\Internal\Message
{
    /**
     * &#64;gotags: gorm:"primaryKey" json:"-"
     *
     * Generated from protobuf field <code>int64 lid = 1;</code>
     */
    protected $lid = 0;
    /**
     * &#64;gotags: json:"main"
     *
     * Generated from protobuf field <code>string main = 2;</code>
     */
    protected $main = '';
    /**
     * &#64;gotags: json:"peer"
     *
     * Generated from protobuf field <code>string peer = 3;</code>
     */
    protected $peer = '';
    /**
     * &#64;gotags: json:"origin"
     *
     * Generated from protobuf field <code>string origin = 4;</code>
     */
    protected $origin = '';
    /**
     * &#64;gotags: json:"team"
     *
     * Generated from protobuf field <code>string team = 5;</code>
     */
    protected $team = '';
    /**
     * &#64;gotags: json:"approved"
     *
     * Generated from protobuf field <code>int64 approved = 6;</code>
     */
    protected $approved = 0;
    /**
     * &#64;gotags: json:"created"
     *
     * Generated from protobuf field <code>int64 created = 7;</code>
     */
    protected $created = 0;
    /**
     * &#64;gotags: json:"updated"
     *
     * Generated from protobuf field <code>int64 updated = 8;</code>
     */
    protected $updated = 0;
    /**
     * &#64;gotags: json:"deleted"
     *
     * Generated from protobuf field <code>int64 deleted = 9;</code>
     */
    protected $deleted = 0;
    /**
     * &#64;gotags: gorm:"serializer:json" json:"attachment"
     *
     * Generated from protobuf field <code>.google.protobuf.Struct attachment = 10;</code>
     */
    protected $attachment = null;
    /**
     * &#64;gotags: json:"has_del"
     *
     * Generated from protobuf field <code>bool has_del = 11;</code>
     */
    protected $has_del = false;
    /**
     * &#64;gotags: json:"unregistered"
     *
     * Generated from protobuf field <code>bool unregistered = 12;</code>
     */
    protected $unregistered = false;
    /**
     * &#64;gotags: gorm:"-" json:"card"
     *
     * Generated from protobuf field <code>.im.v1.Card card = 13;</code>
     */
    protected $card = null;
    /**
     * &#64;gotags: json:"top"
     *
     * Generated from protobuf field <code>bool top = 14;</code>
     */
    protected $top = false;
    /**
     * &#64;gotags: json:"view_history"
     *
     * Generated from protobuf field <code>bool view_history = 15;</code>
     */
    protected $view_history = false;
    /**
     * &#64;gotags: json:"no_disturb"
     *
     * Generated from protobuf field <code>bool no_disturb = 16;</code>
     */
    protected $no_disturb = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $lid
     *           &#64;gotags: gorm:"primaryKey" json:"-"
     *     @type string $main
     *           &#64;gotags: json:"main"
     *     @type string $peer
     *           &#64;gotags: json:"peer"
     *     @type string $origin
     *           &#64;gotags: json:"origin"
     *     @type string $team
     *           &#64;gotags: json:"team"
     *     @type int|string $approved
     *           &#64;gotags: json:"approved"
     *     @type int|string $created
     *           &#64;gotags: json:"created"
     *     @type int|string $updated
     *           &#64;gotags: json:"updated"
     *     @type int|string $deleted
     *           &#64;gotags: json:"deleted"
     *     @type \Google\Protobuf\Struct $attachment
     *           &#64;gotags: gorm:"serializer:json" json:"attachment"
     *     @type bool $has_del
     *           &#64;gotags: json:"has_del"
     *     @type bool $unregistered
     *           &#64;gotags: json:"unregistered"
     *     @type \Im\V1\Card $card
     *           &#64;gotags: gorm:"-" json:"card"
     *     @type bool $top
     *           &#64;gotags: json:"top"
     *     @type bool $view_history
     *           &#64;gotags: json:"view_history"
     *     @type bool $no_disturb
     *           &#64;gotags: json:"no_disturb"
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Im\V1\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * &#64;gotags: gorm:"primaryKey" json:"-"
     *
     * Generated from protobuf field <code>int64 lid = 1;</code>
     * @return int|string
     */
    public function getLid()
    {
        return $this->lid;
    }

    /**
     * &#64;gotags: gorm:"primaryKey" json:"-"
     *
     * Generated from protobuf field <code>int64 lid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLid($var)
    {
        GPBUtil::checkInt64($var);
        $this->lid = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"main"
     *
     * Generated from protobuf field <code>string main = 2;</code>
     * @return string
     */
    public function getMain()
    {
        return $this->main;
    }

    /**
     * &#64;gotags: json:"main"
     *
     * Generated from protobuf field <code>string main = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMain($var)
    {
        GPBUtil::checkString($var, True);
        $this->main = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"peer"
     *
     * Generated from protobuf field <code>string peer = 3;</code>
     * @return string
     */
    public function getPeer()
    {
        return $this->peer;
    }

    /**
     * &#64;gotags: json:"peer"
     *
     * Generated from protobuf field <code>string peer = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPeer($var)
    {
        GPBUtil::checkString($var, True);
        $this->peer = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"origin"
     *
     * Generated from protobuf field <code>string origin = 4;</code>
     * @return string
     */
    public function getOrigin()
    {
        return $this->origin;
    }

    /**
     * &#64;gotags: json:"origin"
     *
     * Generated from protobuf field <code>string origin = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setOrigin($var)
    {
        GPBUtil::checkString($var, True);
        $this->origin = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"team"
     *
     * Generated from protobuf field <code>string team = 5;</code>
     * @return string
     */
    public function getTeam()
    {
        return $this->team;
    }

    /**
     * &#64;gotags: json:"team"
     *
     * Generated from protobuf field <code>string team = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTeam($var)
    {
        GPBUtil::checkString($var, True);
        $this->team = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"approved"
     *
     * Generated from protobuf field <code>int64 approved = 6;</code>
     * @return int|string
     */
    public function getApproved()
    {
        return $this->approved;
    }

    /**
     * &#64;gotags: json:"approved"
     *
     * Generated from protobuf field <code>int64 approved = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setApproved($var)
    {
        GPBUtil::checkInt64($var);
        $this->approved = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"created"
     *
     * Generated from protobuf field <code>int64 created = 7;</code>
     * @return int|string
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * &#64;gotags: json:"created"
     *
     * Generated from protobuf field <code>int64 created = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreated($var)
    {
        GPBUtil::checkInt64($var);
        $this->created = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"updated"
     *
     * Generated from protobuf field <code>int64 updated = 8;</code>
     * @return int|string
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * &#64;gotags: json:"updated"
     *
     * Generated from protobuf field <code>int64 updated = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpdated($var)
    {
        GPBUtil::checkInt64($var);
        $this->updated = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"deleted"
     *
     * Generated from protobuf field <code>int64 deleted = 9;</code>
     * @return int|string
     */
    public function getDeleted()
    {
        return $this->deleted;
    }

    /**
     * &#64;gotags: json:"deleted"
     *
     * Generated from protobuf field <code>int64 deleted = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDeleted($var)
    {
        GPBUtil::checkInt64($var);
        $this->deleted = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"serializer:json" json:"attachment"
     *
     * Generated from protobuf field <code>.google.protobuf.Struct attachment = 10;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getAttachment()
    {
        return $this->attachment;
    }

    public function hasAttachment()
    {
        return isset($this->attachment);
    }

    public function clearAttachment()
    {
        unset($this->attachment);
    }

    /**
     * &#64;gotags: gorm:"serializer:json" json:"attachment"
     *
     * Generated from protobuf field <code>.google.protobuf.Struct attachment = 10;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setAttachment($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->attachment = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"has_del"
     *
     * Generated from protobuf field <code>bool has_del = 11;</code>
     * @return bool
     */
    public function getHasDel()
    {
        return $this->has_del;
    }

    /**
     * &#64;gotags: json:"has_del"
     *
     * Generated from protobuf field <code>bool has_del = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setHasDel($var)
    {
        GPBUtil::checkBool($var);
        $this->has_del = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"unregistered"
     *
     * Generated from protobuf field <code>bool unregistered = 12;</code>
     * @return bool
     */
    public function getUnregistered()
    {
        return $this->unregistered;
    }

    /**
     * &#64;gotags: json:"unregistered"
     *
     * Generated from protobuf field <code>bool unregistered = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setUnregistered($var)
    {
        GPBUtil::checkBool($var);
        $this->unregistered = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"-" json:"card"
     *
     * Generated from protobuf field <code>.im.v1.Card card = 13;</code>
     * @return \Im\V1\Card|null
     */
    public function getCard()
    {
        return $this->card;
    }

    public function hasCard()
    {
        return isset($this->card);
    }

    public function clearCard()
    {
        unset($this->card);
    }

    /**
     * &#64;gotags: gorm:"-" json:"card"
     *
     * Generated from protobuf field <code>.im.v1.Card card = 13;</code>
     * @param \Im\V1\Card $var
     * @return $this
     */
    public function setCard($var)
    {
        GPBUtil::checkMessage($var, \Im\V1\Card::class);
        $this->card = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"top"
     *
     * Generated from protobuf field <code>bool top = 14;</code>
     * @return bool
     */
    public function getTop()
    {
        return $this->top;
    }

    /**
     * &#64;gotags: json:"top"
     *
     * Generated from protobuf field <code>bool top = 14;</code>
     * @param bool $var
     * @return $this
     */
    public function setTop($var)
    {
        GPBUtil::checkBool($var);
        $this->top = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"view_history"
     *
     * Generated from protobuf field <code>bool view_history = 15;</code>
     * @return bool
     */
    public function getViewHistory()
    {
        return $this->view_history;
    }

    /**
     * &#64;gotags: json:"view_history"
     *
     * Generated from protobuf field <code>bool view_history = 15;</code>
     * @param bool $var
     * @return $this
     */
    public function setViewHistory($var)
    {
        GPBUtil::checkBool($var);
        $this->view_history = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"no_disturb"
     *
     * Generated from protobuf field <code>bool no_disturb = 16;</code>
     * @return bool
     */
    public function getNoDisturb()
    {
        return $this->no_disturb;
    }

    /**
     * &#64;gotags: json:"no_disturb"
     *
     * Generated from protobuf field <code>bool no_disturb = 16;</code>
     * @param bool $var
     * @return $this
     */
    public function setNoDisturb($var)
    {
        GPBUtil::checkBool($var);
        $this->no_disturb = $var;

        return $this;
    }

}

