<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/schema.proto

namespace Im\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 关系
 *
 * Generated from protobuf message <code>im.v1.Pair</code>
 */
class Pair extends \Google\Protobuf\Internal\Message
{
    /**
     * &#64;gotags: gorm:"primaryKey" json:"-"
     *
     * Generated from protobuf field <code>int64 lid = 1;</code>
     */
    protected $lid = 0;
    /**
     * 分区键，所有者个人标识符
     *
     * Generated from protobuf field <code>string main = 2;</code>
     */
    protected $main = '';
    /**
     * 接受者个人标识符
     *
     * Generated from protobuf field <code>string peer = 3;</code>
     */
    protected $peer = '';
    /**
     * 来源描述
     *
     * Generated from protobuf field <code>string origin = 4;</code>
     */
    protected $origin = '';
    /**
     * 机构ID，为空表示非机构单聊
     *
     * Generated from protobuf field <code>string team = 5;</code>
     */
    protected $team = '';
    /**
     * 接受者认可的时间戳，>0 表示已通过
     *
     * Generated from protobuf field <code>int64 approved = 6;</code>
     */
    protected $approved = 0;
    /**
     * 创建时间，时间戳
     *
     * Generated from protobuf field <code>int64 created = 7;</code>
     */
    protected $created = 0;
    /**
     * 更新时间，时间戳
     *
     * Generated from protobuf field <code>int64 updated = 8;</code>
     */
    protected $updated = 0;
    /**
     * 删除时间，时间戳
     *
     * Generated from protobuf field <code>int64 deleted = 9;</code>
     */
    protected $deleted = 0;
    /**
     * &#64;gotags: gorm:"serializer:json" json:"attachment"
     *
     * Generated from protobuf field <code>.google.protobuf.Struct attachment = 10;</code>
     */
    protected $attachment = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $lid
     *           &#64;gotags: gorm:"primaryKey" json:"-"
     *     @type string $main
     *           分区键，所有者个人标识符
     *     @type string $peer
     *           接受者个人标识符
     *     @type string $origin
     *           来源描述
     *     @type string $team
     *           机构ID，为空表示非机构单聊
     *     @type int|string $approved
     *           接受者认可的时间戳，>0 表示已通过
     *     @type int|string $created
     *           创建时间，时间戳
     *     @type int|string $updated
     *           更新时间，时间戳
     *     @type int|string $deleted
     *           删除时间，时间戳
     *     @type \Google\Protobuf\Struct $attachment
     *           &#64;gotags: gorm:"serializer:json" json:"attachment"
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Im\V1\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * &#64;gotags: gorm:"primaryKey" json:"-"
     *
     * Generated from protobuf field <code>int64 lid = 1;</code>
     * @return int|string
     */
    public function getLid()
    {
        return $this->lid;
    }

    /**
     * &#64;gotags: gorm:"primaryKey" json:"-"
     *
     * Generated from protobuf field <code>int64 lid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLid($var)
    {
        GPBUtil::checkInt64($var);
        $this->lid = $var;

        return $this;
    }

    /**
     * 分区键，所有者个人标识符
     *
     * Generated from protobuf field <code>string main = 2;</code>
     * @return string
     */
    public function getMain()
    {
        return $this->main;
    }

    /**
     * 分区键，所有者个人标识符
     *
     * Generated from protobuf field <code>string main = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMain($var)
    {
        GPBUtil::checkString($var, True);
        $this->main = $var;

        return $this;
    }

    /**
     * 接受者个人标识符
     *
     * Generated from protobuf field <code>string peer = 3;</code>
     * @return string
     */
    public function getPeer()
    {
        return $this->peer;
    }

    /**
     * 接受者个人标识符
     *
     * Generated from protobuf field <code>string peer = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPeer($var)
    {
        GPBUtil::checkString($var, True);
        $this->peer = $var;

        return $this;
    }

    /**
     * 来源描述
     *
     * Generated from protobuf field <code>string origin = 4;</code>
     * @return string
     */
    public function getOrigin()
    {
        return $this->origin;
    }

    /**
     * 来源描述
     *
     * Generated from protobuf field <code>string origin = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setOrigin($var)
    {
        GPBUtil::checkString($var, True);
        $this->origin = $var;

        return $this;
    }

    /**
     * 机构ID，为空表示非机构单聊
     *
     * Generated from protobuf field <code>string team = 5;</code>
     * @return string
     */
    public function getTeam()
    {
        return $this->team;
    }

    /**
     * 机构ID，为空表示非机构单聊
     *
     * Generated from protobuf field <code>string team = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTeam($var)
    {
        GPBUtil::checkString($var, True);
        $this->team = $var;

        return $this;
    }

    /**
     * 接受者认可的时间戳，>0 表示已通过
     *
     * Generated from protobuf field <code>int64 approved = 6;</code>
     * @return int|string
     */
    public function getApproved()
    {
        return $this->approved;
    }

    /**
     * 接受者认可的时间戳，>0 表示已通过
     *
     * Generated from protobuf field <code>int64 approved = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setApproved($var)
    {
        GPBUtil::checkInt64($var);
        $this->approved = $var;

        return $this;
    }

    /**
     * 创建时间，时间戳
     *
     * Generated from protobuf field <code>int64 created = 7;</code>
     * @return int|string
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * 创建时间，时间戳
     *
     * Generated from protobuf field <code>int64 created = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreated($var)
    {
        GPBUtil::checkInt64($var);
        $this->created = $var;

        return $this;
    }

    /**
     * 更新时间，时间戳
     *
     * Generated from protobuf field <code>int64 updated = 8;</code>
     * @return int|string
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * 更新时间，时间戳
     *
     * Generated from protobuf field <code>int64 updated = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpdated($var)
    {
        GPBUtil::checkInt64($var);
        $this->updated = $var;

        return $this;
    }

    /**
     * 删除时间，时间戳
     *
     * Generated from protobuf field <code>int64 deleted = 9;</code>
     * @return int|string
     */
    public function getDeleted()
    {
        return $this->deleted;
    }

    /**
     * 删除时间，时间戳
     *
     * Generated from protobuf field <code>int64 deleted = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDeleted($var)
    {
        GPBUtil::checkInt64($var);
        $this->deleted = $var;

        return $this;
    }

    /**
     * &#64;gotags: gorm:"serializer:json" json:"attachment"
     *
     * Generated from protobuf field <code>.google.protobuf.Struct attachment = 10;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getAttachment()
    {
        return $this->attachment;
    }

    public function hasAttachment()
    {
        return isset($this->attachment);
    }

    public function clearAttachment()
    {
        unset($this->attachment);
    }

    /**
     * &#64;gotags: gorm:"serializer:json" json:"attachment"
     *
     * Generated from protobuf field <code>.google.protobuf.Struct attachment = 10;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setAttachment($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->attachment = $var;

        return $this;
    }

}

