<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/sync.proto

namespace Im\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * RCNotify 融云通知结构
 *
 * Generated from protobuf message <code>im.v1.RCNotify</code>
 */
class RCNotify extends \Google\Protobuf\Internal\Message
{
    /**
     * &#64;gotags: json:"type"
     *
     * Generated from protobuf field <code>string type = 1;</code>
     */
    protected $type = '';
    /**
     * &#64;gotags: json:"scene"
     *
     * Generated from protobuf field <code>int32 scene = 2;</code>
     */
    protected $scene = 0;
    /**
     * &#64;gotags: json:"content"
     *
     * Generated from protobuf field <code>string content = 3;</code>
     */
    protected $content = '';
    /**
     * &#64;gotags: json:"seq"
     *
     * Generated from protobuf field <code>int64 seq = 4;</code>
     */
    protected $seq = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $type
     *           &#64;gotags: json:"type"
     *     @type int $scene
     *           &#64;gotags: json:"scene"
     *     @type string $content
     *           &#64;gotags: json:"content"
     *     @type int|string $seq
     *           &#64;gotags: json:"seq"
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Im\V1\Sync::initOnce();
        parent::__construct($data);
    }

    /**
     * &#64;gotags: json:"type"
     *
     * Generated from protobuf field <code>string type = 1;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * &#64;gotags: json:"type"
     *
     * Generated from protobuf field <code>string type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"scene"
     *
     * Generated from protobuf field <code>int32 scene = 2;</code>
     * @return int
     */
    public function getScene()
    {
        return $this->scene;
    }

    /**
     * &#64;gotags: json:"scene"
     *
     * Generated from protobuf field <code>int32 scene = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setScene($var)
    {
        GPBUtil::checkInt32($var);
        $this->scene = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"content"
     *
     * Generated from protobuf field <code>string content = 3;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * &#64;gotags: json:"content"
     *
     * Generated from protobuf field <code>string content = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;

        return $this;
    }

    /**
     * &#64;gotags: json:"seq"
     *
     * Generated from protobuf field <code>int64 seq = 4;</code>
     * @return int|string
     */
    public function getSeq()
    {
        return $this->seq;
    }

    /**
     * &#64;gotags: json:"seq"
     *
     * Generated from protobuf field <code>int64 seq = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSeq($var)
    {
        GPBUtil::checkInt64($var);
        $this->seq = $var;

        return $this;
    }

}

