<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/sync.proto

namespace Im\V1;

/**
 * Protobuf type <code>im.v1.TencentSrv</code>
 */
interface TencentSrvInterface
{
    /**
     * VoiceTextResult 语音转文本结果
     *
     * Method <code>voiceTextResult</code>
     *
     * @param \Im\V1\ID $request
     * @return \Im\V1\TextResult
     */
    public function voiceTextResult(\Im\V1\ID $request);

    /**
     * Voice2Text 语音转文本
     *
     * Method <code>voice2Text</code>
     *
     * @param \Im\V1\VoiceText $request
     * @return \Im\V1\ID
     */
    public function voice2Text(\Im\V1\VoiceText $request);

    /**
     * Voice2Text 语音转文本回调
     *
     * Method <code>voice2TextCallback</code>
     *
     * @param \Im\V1\TextCallback $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function voice2TextCallback(\Im\V1\TextCallback $request);

}

