<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/sync.proto

namespace Im\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ThirdMessage 融云消息推送
 *
 * Generated from protobuf message <code>im.v1.ThirdMessage</code>
 */
class ThirdMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 是否系统通知
     *
     * Generated from protobuf field <code>bool notify = 1;</code>
     */
    protected $notify = false;
    /**
     * 消息类型
     *
     * Generated from protobuf field <code>string typ = 2;</code>
     */
    protected $typ = '';
    /**
     * 消息内容
     *
     * Generated from protobuf field <code>string content = 3;</code>
     */
    protected $content = '';
    /**
     * 消息接收者
     *
     * Generated from protobuf field <code>repeated string users = 4;</code>
     */
    private $users;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $notify
     *           是否系统通知
     *     @type string $typ
     *           消息类型
     *     @type string $content
     *           消息内容
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $users
     *           消息接收者
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Im\V1\Sync::initOnce();
        parent::__construct($data);
    }

    /**
     * 是否系统通知
     *
     * Generated from protobuf field <code>bool notify = 1;</code>
     * @return bool
     */
    public function getNotify()
    {
        return $this->notify;
    }

    /**
     * 是否系统通知
     *
     * Generated from protobuf field <code>bool notify = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setNotify($var)
    {
        GPBUtil::checkBool($var);
        $this->notify = $var;

        return $this;
    }

    /**
     * 消息类型
     *
     * Generated from protobuf field <code>string typ = 2;</code>
     * @return string
     */
    public function getTyp()
    {
        return $this->typ;
    }

    /**
     * 消息类型
     *
     * Generated from protobuf field <code>string typ = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTyp($var)
    {
        GPBUtil::checkString($var, True);
        $this->typ = $var;

        return $this;
    }

    /**
     * 消息内容
     *
     * Generated from protobuf field <code>string content = 3;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * 消息内容
     *
     * Generated from protobuf field <code>string content = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;

        return $this;
    }

    /**
     * 消息接收者
     *
     * Generated from protobuf field <code>repeated string users = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUsers()
    {
        return $this->users;
    }

    /**
     * 消息接收者
     *
     * Generated from protobuf field <code>repeated string users = 4;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUsers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->users = $arr;

        return $this;
    }

}

