<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/sync.proto

namespace Im\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ThirdMessage 融云消息推送
 *
 * Generated from protobuf message <code>im.v1.ThirdMessage</code>
 */
class ThirdMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 是否系统通知
     *
     * Generated from protobuf field <code>bool notify = 1;</code>
     */
    protected $notify = false;
    /**
     * 发送者
     *
     * Generated from protobuf field <code>string sender = 2;</code>
     */
    protected $sender = '';
    /**
     * 消息内容
     *
     * Generated from protobuf field <code>.im.v1.RCNotify content = 3;</code>
     */
    protected $content = null;
    /**
     * 消息接收者
     *
     * Generated from protobuf field <code>repeated string users = 4;</code>
     */
    private $users;
    /**
     * 通知序号，红点
     *
     * Generated from protobuf field <code>int64 seq = 5;</code>
     */
    protected $seq = 0;
    /**
     * 通知栏提醒内容
     *
     * Generated from protobuf field <code>string notify_content = 6;</code>
     */
    protected $notify_content = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $notify
     *           是否系统通知
     *     @type string $sender
     *           发送者
     *     @type \Im\V1\RCNotify $content
     *           消息内容
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $users
     *           消息接收者
     *     @type int|string $seq
     *           通知序号，红点
     *     @type string $notify_content
     *           通知栏提醒内容
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Im\V1\Sync::initOnce();
        parent::__construct($data);
    }

    /**
     * 是否系统通知
     *
     * Generated from protobuf field <code>bool notify = 1;</code>
     * @return bool
     */
    public function getNotify()
    {
        return $this->notify;
    }

    /**
     * 是否系统通知
     *
     * Generated from protobuf field <code>bool notify = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setNotify($var)
    {
        GPBUtil::checkBool($var);
        $this->notify = $var;

        return $this;
    }

    /**
     * 发送者
     *
     * Generated from protobuf field <code>string sender = 2;</code>
     * @return string
     */
    public function getSender()
    {
        return $this->sender;
    }

    /**
     * 发送者
     *
     * Generated from protobuf field <code>string sender = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSender($var)
    {
        GPBUtil::checkString($var, True);
        $this->sender = $var;

        return $this;
    }

    /**
     * 消息内容
     *
     * Generated from protobuf field <code>.im.v1.RCNotify content = 3;</code>
     * @return \Im\V1\RCNotify|null
     */
    public function getContent()
    {
        return $this->content;
    }

    public function hasContent()
    {
        return isset($this->content);
    }

    public function clearContent()
    {
        unset($this->content);
    }

    /**
     * 消息内容
     *
     * Generated from protobuf field <code>.im.v1.RCNotify content = 3;</code>
     * @param \Im\V1\RCNotify $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkMessage($var, \Im\V1\RCNotify::class);
        $this->content = $var;

        return $this;
    }

    /**
     * 消息接收者
     *
     * Generated from protobuf field <code>repeated string users = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUsers()
    {
        return $this->users;
    }

    /**
     * 消息接收者
     *
     * Generated from protobuf field <code>repeated string users = 4;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUsers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->users = $arr;

        return $this;
    }

    /**
     * 通知序号，红点
     *
     * Generated from protobuf field <code>int64 seq = 5;</code>
     * @return int|string
     */
    public function getSeq()
    {
        return $this->seq;
    }

    /**
     * 通知序号，红点
     *
     * Generated from protobuf field <code>int64 seq = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSeq($var)
    {
        GPBUtil::checkInt64($var);
        $this->seq = $var;

        return $this;
    }

    /**
     * 通知栏提醒内容
     *
     * Generated from protobuf field <code>string notify_content = 6;</code>
     * @return string
     */
    public function getNotifyContent()
    {
        return $this->notify_content;
    }

    /**
     * 通知栏提醒内容
     *
     * Generated from protobuf field <code>string notify_content = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setNotifyContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->notify_content = $var;

        return $this;
    }

}

