<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/schema.proto

namespace Im\V1;

if (false) {
    /**
     * This class is deprecated. Use Im\V1\Unified\Options\AlertMode instead.
     * @deprecated
     */
    class Unified_Options_AlertMode {}
}
class_exists(Unified\Options\AlertMode::class);
@trigger_error('Im\V1\Unified_Options_AlertMode is deprecated and will be removed in the next major release. Use Im\V1\Unified\Options\AlertMode instead', E_USER_DEPRECATED);

