<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/schema.proto

namespace Im\V1;

if (false) {
    /**
     * This class is deprecated. Use Im\V1\User\Short instead.
     * @deprecated
     */
    class User_Short {}
}
class_exists(User\Short::class);
@trigger_error('Im\V1\User_Short is deprecated and will be removed in the next major release. Use Im\V1\User\Short instead', E_USER_DEPRECATED);

