<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/schema.proto

namespace Im\V1;

if (false) {
    /**
     * This class is deprecated. Use Im\V1\User\Full\Type instead.
     * @deprecated
     */
    class User_Full_Type {}
}
class_exists(User\Full\Type::class);
@trigger_error('Im\V1\User_Full_Type is deprecated and will be removed in the next major release. Use Im\V1\User\Full\Type instead', E_USER_DEPRECATED);

