<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/schema.proto

namespace Im\V1;

if (false) {
    /**
     * This class is deprecated. Use Im\V1\User\Full instead.
     * @deprecated
     */
    class User_Full {}
}
class_exists(User\Full::class);
@trigger_error('Im\V1\User_Full is deprecated and will be removed in the next major release. Use Im\V1\User\Full instead', E_USER_DEPRECATED);

