<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im/v1/schema.proto

namespace Im\V1\Unified;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>im.v1.Unified.Options</code>
 */
class Options extends \Google\Protobuf\Internal\Message
{
    /**
     * 新消息提示等级
     *
     * Generated from protobuf field <code>.im.v1.Unified.Options.AlertMode alert = 1;</code>
     */
    protected $alert = 0;
    /**
     * 铃声，此消息使用的特定的铃声
     *
     * Generated from protobuf field <code>uint64 bell = 2;</code>
     */
    protected $bell = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $alert
     *           新消息提示等级
     *     @type int|string $bell
     *           铃声，此消息使用的特定的铃声
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Im\V1\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * 新消息提示等级
     *
     * Generated from protobuf field <code>.im.v1.Unified.Options.AlertMode alert = 1;</code>
     * @return int
     */
    public function getAlert()
    {
        return $this->alert;
    }

    /**
     * 新消息提示等级
     *
     * Generated from protobuf field <code>.im.v1.Unified.Options.AlertMode alert = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAlert($var)
    {
        GPBUtil::checkEnum($var, \Im\V1\Unified\Options\AlertMode::class);
        $this->alert = $var;

        return $this;
    }

    /**
     * 铃声，此消息使用的特定的铃声
     *
     * Generated from protobuf field <code>uint64 bell = 2;</code>
     * @return int|string
     */
    public function getBell()
    {
        return $this->bell;
    }

    /**
     * 铃声，此消息使用的特定的铃声
     *
     * Generated from protobuf field <code>uint64 bell = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBell($var)
    {
        GPBUtil::checkUint64($var);
        $this->bell = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Options::class, \Im\V1\Unified_Options::class);

